export const Majors = [
  {
    "name": "Agricultural Science",
    "core": [
      " Agricultural Systems Analysis ",
      " Livestock Production Systems ",
      " Plant Pathology ",
      " Irrigation and Water Management ",
      " Soil Management ",
      " Managing Production Animal Health ",
      " Applications in Precision Agriculture ",
    ],
  },
  {
    "name": "Animal Health and Disease",
    "core": [
      " Foundations of Animal Health 1 ",
      " Foundations of Animal Health 2 ",
      " Biochemistry and Molecular Biology ",
      " Veterinary Bioscience: Cells to Systems ",
      " Veterinary Bioscience: Digestive System ",
      " Veterinary Bioscience: Metabolism ",
      " Veterinary Bioscience: Cardiovasc System ",
      " Veterinary Bioscience:Respiratory System ",
      " Animal Health in Production Systems ",
      " Veterinary Bioscience: Cells to Systems ",
      " Animal Disease Biotechnology 1 ",
      " Animal Disease Biotechnology 2 ",
      " Animal Systems Analysis ",
      " Applied Animal Behaviour ",
      " Livestock Production Systems ",
      " Animal Welfare and Ethics ",
      " Medical Microbiology: Virology ",
      " Animal Behaviour ",
      " Tropical Field Ecology ",
      " Frontiers in Physiology ",
      " Applied Animal Reproduction  Genetics ",
    ],
  },
  {
    "name": "Animal Science and Management",
    "core": [
      " Animal Systems Analysis ",
      " Applied Animal Behaviour ",
      " Livestock Production Systems ",
      " Animal Disease Biotechnology 1 ",
      " Animal Disease Biotechnology 2 ",
      " Applied Animal Reproduction  Genetics ",
      " Production Animal Physiology ",
      " Production Animal Health ",
      " Managing Production Animal Health ",
      " Applications in Precision Agriculture ",
    ],
  },
  {
    "name": "Biochemistry and Molecular Biology",
    "core": [
      " Protein Structure and Function ",
      " Functional Genomics and Bioinformatics ",
      " Molecular Aspects of Cell Biology ",
      " Cell Signalling and Neurochemistry ",
      " Cellular Metabolism and Disease ",
      " Biomedical Science Research Project ",
      " Medical Microbiology: Parasitology ",
    ],
  },
  {
    "name": "Bioengineering Systems",
    "core": [
      " Biosystems Design ",
      " Introduction to Biomaterials ",
      " Introduction to Biomaterials ",
    ],
  },
  {
    "name": "Biotechnology",
    "core": [
      " Trends  Issues in Agrifood Biotech ",
      " Functional Foods ",
      " Functional Genomics and Bioinformatics ",
      " Biotechnology in Practice ",
      " Animal Disease Biotechnology 1 ",
      " Animal Disease Biotechnology 2 ",
      " Biotechnology in Practice ",
      " Protein Structure and Function ",
      " Advanced Techniques in Molecular Science ",
      " Functional Genomics and Bioinformatics ",
      " Biotechnology in Practice ",
      " Principles of Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Techniques in Immunology ",
      " Techniques in Microbiology ",
      " Biotechnology in Practice ",
      " Drugs in Biomedical Experiments ",
      " Drug Treatment of Disease ",
      " Drugs Affecting the Nervous System ",
      " Drugs: From Discovery to Market ",
      " Biotechnology in Practice ",
      " Concepts in Cell  Developmental Biology ",
      " Developmental Biology ",
      " Reproductive Physiology ",
      " Molecular Aspects of Cell Biology ",
      " Genes: Organisation and Function ",
      " Experimental Reproductive Physiology ",
      " Plant Molecular Biology  Biotechnology ",
      " Stem Cells in Development  Regeneration ",
      " Biotechnology in Practice ",
      " Genes: Organisation and Function ",
      " Evolutionary Genetics and Genomics ",
      " Genetic Analysis ",
      " Biotechnology in Practice ",
      " Reactivity and Mechanism ",
      " Analytical  Environmental Chemistry ",
      " Specialised Topics in Chemistry  ",
      " Specialised Topics in Chemistry  ",
    ],
  },
  {
    "name": "Cell and Developmental Biology",
    "core": [
      " Concepts in Cell  Developmental Biology ",
      " Functional Genomics and Bioinformatics ",
      " Cell Signalling and Neurochemistry ",
      " Experimental Reproductive Physiology ",
      " Biomedical Science Research Project ",
      " Genes: Organisation and Function ",
      " Principles of Immunology ",
      " Developmental Neurobiology ",
      " Neurophysiology: Neurons and Circuits ",
      " Mechanisms of Human Disease ",
    ],
  },
  {
    "name": "Chemical Systems",
    "core": [
      " Reactor Engineering ",
      " Heat and Mass Transport Processes ",
      " Safety and Sustainability Case Studies ",
      " Fluid Mechanics ",
    ],
  },
  {
    "name": "Chemistry",
    "core": [
      " Advanced Practical Chemistry ",
      " Reactivity and Mechanism ",
      " Specialised Topics in Chemistry  ",
      " Specialised Topics in Chemistry  ",
      " Analytical  Environmental Chemistry ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Physics 11: Fundamentals ",
      " Reactivity and Mechanism ",
      " Advanced Practical Chemistry ",
      " Drugs: From Discovery to Market ",
      " Drugs in Biomedical Experiments ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Physics 11: Fundamentals ",
    ],
  },
  {
    "name": "Civil Systems",
    "core": [
      " Engineering Risk Analysis ",
      " Systems Modelling and Design ",
      " Structural Theory and Design ",
      " Fluid Mechanics ",
    ],
  },
  { "name": "Climate and Weather", "core": [] },
  { "name": "Computational Biology", "core": [] },
  {
    "name": "Computing and Software Systems",
    "core": [
      " Software Modelling and Design ",
      " Computer Systems ",
      " IT Project ",
      " Models of Computation ",
    ],
  },
  {
    "name": "Data Science",
    "core": [
      " Machine Learning ",
      " Linear Statistical Models ",
      " Modern Applied Statistics ",
      " Applied Data Science ",
    ],
  },
  {
    "name": "Ecology and Evolutionary Biology",
    "core": [" Ecology in Changing Environments "],
  },
  {
    "name": "Ecosystem Science",
    "core": [
      " Landscape Ecosystem Project ",
      " Green Infrastructure Technologies ",
      " Urban Forest Ecosystems ",
      " Ecology of Urban Landscapes ",
      " Landscape Ecosystem Project ",
      " Forest Systems ",
      " Vegetation Management and Conservation ",
      " Field Botany ",
      " Applied Ecology ",
      " Environmental Risk Assessment ",
      " Urban Forest Ecosystems ",
      " Nature, Conservation and Society ",
    ],
  },
  {
    "name": "Electrical Systems",
    "core": [
      " Electrical Network Analysis and Design ",
      " Electrical Device Modelling ",
      " Signals and Systems ",
      " Electronic System Implementation ",
    ],
  },
  {
    "name": "Environmental Engineering Systems",
    "core": [
      " Fluid Mechanics ",
      " Biotransport Processes ",
      " Environmental Eng Systems Capstone ",
      " Systems Modelling and Design ",
    ],
  },
  {
    "name": "Environmental Science",
    "core": [
      " Environmental Risk Assessment ",
      " Problem Solving in Environmental Science ",
      " Vegetation Management and Conservation ",
      " Applied Ecology ",
      " Ecology in Changing Environments ",
      " Marine Ecosystems: Ecology  Management ",
      " Green Infrastructure Technologies ",
      " Ecology of Urban Landscapes ",
      " Landscape Ecosystem Project ",
      " Forest Systems ",
      " Urban Forest Ecosystems ",
      " Riverine Landscapes: Hydrology  Ecology ",
      " Biogeography and Ecology of Fire ",
      " Geobiology: Fossils  Environments ",
      " Environmental Risk Assessment ",
      " Problem Solving in Environmental Science ",
      " Atmospheric Processes and Composition ",
      " Analytical  Environmental Chemistry ",
      " Hydrogeology/Environmental Geochemistry ",
      " Landscape Ecosystem Project ",
      " Geomorphology: Catchment to Coast ",
      " Tectonics  Geodynamics ",
      " Sedimentary Geology ",
      " Applied Geophysics ",
      " Geobiology: Fossils  Environments ",
      " Imaging the Environment ",
      " The Disaster Resilient City ",
      " Environmental Risk Assessment ",
      " Problem Solving in Environmental Science ",
      " Dynamical Meteorology and Oceanography ",
      " Atmosphere Ocean Interaction ",
      " Ecology in Changing Environments ",
      " Global Climate Change in Context ",
      " Environmental Risk Assessment ",
      " Problem Solving in Environmental Science ",
      " Nature, Conservation and Society ",
      " Sustainable Development ",
    ],
  },
  {
    "name": "Food Science",
    "core": [
      " Advanced Food Analysis ",
      " Food Processing  Preservation ",
      " Food Research  Development ",
      " Functional Foods ",
    ],
  },
  { "name": "Forest Science", "core": [] },
  {
    "name": "Genetics",
    "core": [
      " Evolutionary Genetics and Genomics ",
      " Genes: Organisation and Function ",
      " Genetic Analysis ",
      " Molecular Aspects of Cell Biology ",
      " Concepts in Cell  Developmental Biology ",
      " Ecology in Changing Environments ",
      " Evolution and the Human Condition ",
      " Medical Microbiology: Bacteriology ",
      " Plant Evolution ",
      " Principles of Immunology ",
      " Protein Structure and Function ",
      " Human and Medical Genetics ",
      " Reproductive Physiology ",
      " Science Research Project ",
      " Science and Technology Internship ",
    ],
  },
  {
    "name": "Geography",
    "core": [
      " Global Climate Change in Context ",
      " Biogeography and Ecology of Fire ",
      " China Field Class ",
      " East Timor Field Class ",
      " Local Sites, Global Connections ",
      " Arid Australia Field Class ",
      " Geomorphology: Catchment to Coast ",
      " Sustainable Development ",
      " The Disaster Resilient City ",
      " Riverine Landscapes: Hydrology  Ecology ",
      " Africa: Environment, Development, People ",
      " Spatial Modelling for Nature and People ",
    ],
  },
  {
    "name": "Geology",
    "core": [
      " Tectonics  Geodynamics ",
      " Sedimentary Geology ",
      " Hydrogeology/Environmental Geochemistry ",
      " Geochemistry  Petrogenesis ",
      " Applied Geophysics ",
      " Economic Geology ",
      " Advanced Field Geology ",
      " Science Research Project ",
      " Geobiology: Fossils  Environments ",
    ],
  },
  {
    "name": "Human Nutrition",
    "core": [
      " Advanced Topics in Nutrition ",
      " Monitoring Food and Nutrition Intake ",
      " Lifestage Nutrition ",
      " Molecular Nutrition and Genomics ",
      " Cellular Metabolism and Disease ",
    ],
  },
  {
    "name": "Human Structure and Function",
    "core": [
      " Human Locomotor Systems ",
      " Viscera and Visceral Systems ",
      " Developmental Neurobiology ",
      " Developmental Biology ",
      " Visual Neuroscience ",
      " Mechanisms of Human Disease ",
      " Principles of Neuroscience ",
      " Neurophysiology: Neurons and Circuits ",
      " Techniques for Investigation of Disease ",
      " Biomedical Science Research Project ",
      " Advanced Human Physiology ",
      " Clinical and Translational Physiology ",
      " Physiology: Adapting to Challenges ",
    ],
  },
  {
    "name": "Immunology",
    "core": [
      " Principles of Immunology ",
      " Medical and Applied Immunology ",
      " Techniques in Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Protein Structure and Function ",
      " Functional Genomics and Bioinformatics ",
      " Molecular Aspects of Cell Biology ",
      " Cell Signalling and Neurochemistry ",
      " Genes: Organisation and Function ",
      " Concepts in Cell  Developmental Biology ",
      " Mechanisms of Human Disease ",
      " Medical Microbiology: Parasitology ",
      " Principles of Neuroscience ",
      " Cellular Metabolism and Disease ",
      " Drug Treatment of Disease ",
    ],
  },
  {
    "name": "Infection and Immunity",
    "core": [
      " Principles of Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Medical Microbiology: Parasitology ",
    ],
  },
  { "name": "Informatics", "core": [] },
  {
    "name": "Marine Biology",
    "core": [
      " Marine Botany ",
      " Marine Ecosystems: Ecology  Management ",
      " Experimental Marine Biology ",
      " Analytical  Environmental Chemistry ",
      " Applied Ecology ",
      " Ecology in Changing Environments ",
      " Geomorphology: Catchment to Coast ",
      " Imaging the Environment ",
    ],
  },
  {
    "name": "Mathematical Physics",
    "core": [" Quantum Physics ", " Complex Analysis "],
  },
  {
    "name": "Mathematics and Statistics",
    "core": [
      " Complex Analysis ",
      " Metric and Hilbert Spaces ",
      " Algebra ",
      " Graph Theory ",
      " Discrete Mathematics ",
      " Geometry ",
      " Complex Analysis ",
      " Numerical Methods  Scientific Computing ",
      " Stochastic Modelling ",
      " Applied Mathematical Modelling ",
      " Methods of Mathematical Physics ",
      " Discrete Mathematics ",
      " Techniques in Operations Research ",
      " Complex Analysis ",
      " Stochastic Modelling ",
      " Graph Theory ",
      " Decision Making ",
      " Linear Statistical Models ",
      " Linear Statistical Models ",
      " Stochastic Modelling ",
      " Probability for Inference ",
      " Modern Applied Statistics ",
    ],
  },
  {
    "name": "Mechanical Systems",
    "core": [
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Systems Design ",
      " Systems Modelling and Analysis ",
    ],
  },
  {
    "name": "Mechatronics Systems",
    "core": [
      " Analog and Digital Electronics Concepts ",
      " Numerical Programming for Engineers ",
      " Systems Modelling and Analysis ",
      " Mechanical Systems Design ",
    ],
  },
  {
    "name": "Microbiology",
    "core": [
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Medical Microbiology: Parasitology ",
      " Techniques in Microbiology ",
    ],
  },
  {
    "name": "Neuroscience",
    "core": [
      " Neurophysiology: Neurons and Circuits ",
      " Principles of Neuroscience ",
      " Developmental Neurobiology ",
      " Complex Functions in Neuroscience ",
      " Visual Neuroscience ",
      " Drugs Affecting the Nervous System ",
      " Cell Signalling and Neurochemistry ",
      " Biomedical Science Research Project ",
      " Real and Artificial Neural Networks ",
      " Auditory Neuroscience ",
    ],
  },
  {
    "name": "Pathology",
    "core": [
      " Mechanisms of Human Disease ",
      " Techniques for Investigation of Disease ",
      " Frontiers in Human Disease ",
      " Advanced Investigation of Human Disease ",
      " Biomedical Science Research Project ",
    ],
  },
  {
    "name": "Pharmacology",
    "core": [
      " Drugs in Biomedical Experiments ",
      " Drugs Affecting the Nervous System ",
      " Drug Treatment of Disease ",
      " Drugs: From Discovery to Market ",
    ],
  },
  {
    "name": "Physics",
    "core": [
      " Quantum Physics ",
      " Reactivity and Mechanism ",
      " Electrodynamics ",
      " Statistical Physics ",
      " Quantum Physics ",
      " Laboratory and Computational Physics 3 ",
      " Statistical Physics ",
      " Electrodynamics ",
    ],
  },
  {
    "name": "Physiology",
    "core": [
      " Advanced Human Physiology ",
      " Human Locomotor Systems ",
      " Viscera and Visceral Systems ",
      " Reproductive Physiology ",
      " Neurophysiology: Neurons and Circuits ",
      " Principles of Neuroscience ",
      " Complex Functions in Neuroscience ",
      " Experimental Physiology ",
      " Biomedical Science Research Project ",
      " Mechanisms of Human Disease ",
      " Drug Treatment of Disease ",
      " Clinical and Translational Physiology ",
      " Physiology: Adapting to Challenges ",
    ],
  },
  {
    "name": "Plant Science",
    "core": [
      " Plant Evolution ",
      " Marine Botany ",
      " Vegetation Management and Conservation ",
      " Plant Molecular Biology  Biotechnology ",
      " Field Botany ",
      " Science Research Project ",
      " Plant Pathology ",
      " Ecology in Changing Environments ",
      " Forest Systems ",
    ],
  },
  {
    "name": "Psychology",
    "core": [
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
      " Research Methods for Human Inquiry ",
      " Psychological Science: Theory  Practice ",
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
    ],
  },
  {
    "name": "Spatial Systems",
    "core": [
      " Engineering Risk Analysis ",
      " Imaging the Environment ",
      " Integrated Spatial Systems ",
      " Land Administration Systems ",
    ],
  },
  {
    "name": "Veterinary BioSciences",
    "core": [
      " Veterinary Bioscience:Respiratory System ",
      " Veterinary Bioscience: Cells to Systems ",
      " Animal Production Systems 2 ",
      " Introduction to Professional Practice ",
      " Animal Production Systems 1 ",
      " Veterinary Bioscience: Cardiovasc System ",
      " Veterinary Bioscience: Digestive System ",
      " Veterinary Bioscience: Metabolism ",
    ],
  },
  {
    "name": "Zoology",
    "core": [
      " Experimental Reproductive Physiology ",
      " Experimental Animal Behaviour ",
      " Experimental Marine Biology ",
      " Tropical Field Ecology ",
      " Reproductive Physiology ",
      " Experimental Reproductive Physiology ",
      " Developmental Biology ",
      " Applied Ecology ",
      " Ecology in Changing Environments ",
      " Marine Ecosystems: Ecology  Management ",
      " Evolutionary Genetics and Genomics ",
      " Science Research Project ",
      " Evolution and the Human Condition ",
      " Animal Behaviour ",
      " Experimental Animal Behaviour ",
      " Experimental Marine Biology ",
      " Tropical Field Ecology ",
    ],
  },
  {
    "name": "Accounting",
    "core": [
      " Accounting Reports and Analysis ",
      " Introductory Financial Accounting ",
      " Cost Management ",
      " Intermediate Financial Accounting ",
      " Accounting Information: Risks  Controls ",
    ],
  },
  {
    "name": "Actuarial Studies",
    "core": [
      " Introductory Financial Mathematics ",
      " Stochastic Techniques in Insurance ",
      " Topics in Actuarial Studies ",
      " Actuarial Modelling  ",
      " Actuarial Modelling II ",
      " Contingencies ",
      " Actuarial Statistics ",
      " Intermediate Financial Mathematics ",
      " Actuarial Modelling III ",
      " Actuarial Analytics and Data  ",
    ],
  },
  { "name": "Economics", "core": [] },
  {
    "name": "Finance",
    "core": [
      " Investments ",
      " Derivative Securities ",
      " Entrepreneurial Finance ",
      " Street Finance ",
      " Ethics in Finance ",
      " Algorithmic Trading ",
      " Essentials of Corporate Valuation ",
      " Foundations of FinTech ",
    ],
  },
  {
    "name": "Management",
    "core": [
      " Business Judgement ",
      " Managing Globally ",
      " Managing Entrepreneurship and Innovation ",
      " Managing Supply Chain Networks ",
      " Management Consulting ",
      " Managing for Competitive Advantage ",
      " Managing Work and Your Career ",
      " Global Management Consulting ",
      " The Future of Work ",
    ],
  },
  {
    "name": "Marketing",
    "core": [
      " Business Judgement ",
      " Service and Relationship Marketing ",
      " Retailing ",
      " Digital Marketing ",
      " Advertising and Promotions ",
      " Product Management ",
      " Business and Marketing Ethics ",
    ],
  },
  {
    "name": "Biochemistry and Molecular Biology",
    "core": [
      " Protein Structure and Function ",
      " Functional Genomics and Bioinformatics ",
      " Molecular Aspects of Cell Biology ",
      " Cell Signalling and Neurochemistry ",
      " Cellular Metabolism and Disease ",
      " Biomedical Science Research Project ",
      " Medical Microbiology: Parasitology ",
    ],
  },
  {
    "name": "Bioengineering Systems",
    "core": [
      " Biosystems Design ",
      " Introduction to Biomaterials ",
      " Introduction to Biomaterials ",
    ],
  },
  {
    "name": "Biotechnology",
    "core": [
      " Trends  Issues in Agrifood Biotech ",
      " Functional Foods ",
      " Functional Genomics and Bioinformatics ",
      " Biotechnology in Practice ",
      " Animal Disease Biotechnology 1 ",
      " Animal Disease Biotechnology 2 ",
      " Biotechnology in Practice ",
      " Protein Structure and Function ",
      " Advanced Techniques in Molecular Science ",
      " Functional Genomics and Bioinformatics ",
      " Biotechnology in Practice ",
      " Principles of Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Techniques in Immunology ",
      " Techniques in Microbiology ",
      " Biotechnology in Practice ",
      " Drugs in Biomedical Experiments ",
      " Drug Treatment of Disease ",
      " Drugs Affecting the Nervous System ",
      " Drugs: From Discovery to Market ",
      " Biotechnology in Practice ",
      " Concepts in Cell  Developmental Biology ",
      " Developmental Biology ",
      " Reproductive Physiology ",
      " Molecular Aspects of Cell Biology ",
      " Genes: Organisation and Function ",
      " Experimental Reproductive Physiology ",
      " Plant Molecular Biology  Biotechnology ",
      " Stem Cells in Development  Regeneration ",
      " Biotechnology in Practice ",
      " Genes: Organisation and Function ",
      " Evolutionary Genetics and Genomics ",
      " Genetic Analysis ",
      " Biotechnology in Practice ",
      " Reactivity and Mechanism ",
      " Analytical  Environmental Chemistry ",
      " Specialised Topics in Chemistry  ",
      " Specialised Topics in Chemistry  ",
    ],
  },
  {
    "name": "Cell and Developmental Biology",
    "core": [
      " Concepts in Cell  Developmental Biology ",
      " Functional Genomics and Bioinformatics ",
      " Cell Signalling and Neurochemistry ",
      " Experimental Reproductive Physiology ",
      " Biomedical Science Research Project ",
      " Genes: Organisation and Function ",
      " Principles of Immunology ",
      " Developmental Neurobiology ",
      " Neurophysiology: Neurons and Circuits ",
      " Mechanisms of Human Disease ",
    ],
  },
  {
    "name": "Genetics",
    "core": [
      " Evolutionary Genetics and Genomics ",
      " Genes: Organisation and Function ",
      " Genetic Analysis ",
      " Molecular Aspects of Cell Biology ",
      " Concepts in Cell  Developmental Biology ",
      " Ecology in Changing Environments ",
      " Evolution and the Human Condition ",
      " Medical Microbiology: Bacteriology ",
      " Plant Evolution ",
      " Principles of Immunology ",
      " Protein Structure and Function ",
      " Human and Medical Genetics ",
      " Reproductive Physiology ",
      " Science Research Project ",
      " Science and Technology Internship ",
    ],
  },
  {
    "name": "Human Nutrition",
    "core": [
      " Advanced Topics in Nutrition ",
      " Monitoring Food and Nutrition Intake ",
      " Lifestage Nutrition ",
      " Molecular Nutrition and Genomics ",
      " Cellular Metabolism and Disease ",
    ],
  },
  {
    "name": "Human Structure and Function",
    "core": [
      " Human Locomotor Systems ",
      " Viscera and Visceral Systems ",
      " Developmental Neurobiology ",
      " Developmental Biology ",
      " Visual Neuroscience ",
      " Mechanisms of Human Disease ",
      " Principles of Neuroscience ",
      " Neurophysiology: Neurons and Circuits ",
      " Techniques for Investigation of Disease ",
      " Biomedical Science Research Project ",
      " Advanced Human Physiology ",
      " Clinical and Translational Physiology ",
      " Physiology: Adapting to Challenges ",
    ],
  },
  {
    "name": "Immunology",
    "core": [
      " Principles of Immunology ",
      " Medical and Applied Immunology ",
      " Techniques in Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Protein Structure and Function ",
      " Functional Genomics and Bioinformatics ",
      " Molecular Aspects of Cell Biology ",
      " Cell Signalling and Neurochemistry ",
      " Genes: Organisation and Function ",
      " Concepts in Cell  Developmental Biology ",
      " Mechanisms of Human Disease ",
      " Medical Microbiology: Parasitology ",
      " Principles of Neuroscience ",
      " Cellular Metabolism and Disease ",
      " Drug Treatment of Disease ",
    ],
  },
  {
    "name": "Infection and Immunity",
    "core": [
      " Principles of Immunology ",
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Medical Microbiology: Parasitology ",
    ],
  },
  {
    "name": "Microbiology",
    "core": [
      " Medical Microbiology: Bacteriology ",
      " Medical Microbiology: Virology ",
      " Medical Microbiology: Parasitology ",
      " Techniques in Microbiology ",
    ],
  },
  {
    "name": "Neuroscience",
    "core": [
      " Neurophysiology: Neurons and Circuits ",
      " Principles of Neuroscience ",
      " Developmental Neurobiology ",
      " Complex Functions in Neuroscience ",
      " Visual Neuroscience ",
      " Drugs Affecting the Nervous System ",
      " Cell Signalling and Neurochemistry ",
      " Biomedical Science Research Project ",
      " Real and Artificial Neural Networks ",
      " Auditory Neuroscience ",
    ],
  },
  {
    "name": "Pathology",
    "core": [
      " Mechanisms of Human Disease ",
      " Techniques for Investigation of Disease ",
      " Frontiers in Human Disease ",
      " Advanced Investigation of Human Disease ",
      " Biomedical Science Research Project ",
    ],
  },
  {
    "name": "Pharmacology",
    "core": [
      " Drugs in Biomedical Experiments ",
      " Drugs Affecting the Nervous System ",
      " Drug Treatment of Disease ",
      " Drugs: From Discovery to Market ",
    ],
  },
  {
    "name": "Physiology",
    "core": [
      " Advanced Human Physiology ",
      " Human Locomotor Systems ",
      " Viscera and Visceral Systems ",
      " Reproductive Physiology ",
      " Neurophysiology: Neurons and Circuits ",
      " Principles of Neuroscience ",
      " Complex Functions in Neuroscience ",
      " Experimental Physiology ",
      " Biomedical Science Research Project ",
      " Mechanisms of Human Disease ",
      " Drug Treatment of Disease ",
      " Clinical and Translational Physiology ",
      " Physiology: Adapting to Challenges ",
    ],
  },
  {
    "name": "Psychology",
    "core": [
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
      " Research Methods for Human Inquiry ",
      " Psychological Science: Theory  Practice ",
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
    ],
  },
  {
    "name": "Architecture",
    "core": [
      " Construction Design ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Civil Systems",
    "core": [
      " Engineering Risk Analysis ",
      " Systems Modelling and Design ",
      " Structural Theory and Design ",
      " Fluid Mechanics ",
    ],
  },
  {
    "name": "Computing",
    "core": [
      " Web Information Technologies ",
      " Computer Systems ",
      " IT Project ",
      " Graphics and Interaction ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Construction",
    "core": [
      " Construction Management ",
      " Steel and Concrete Structural Systems ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Digital Technologies",
    "core": [
      " Web Information Technologies ",
      " Game Design ",
      " Interactive Technology Project ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Graphic Design",
    "core": [
      " Infographics Studio ",
      " Branding ",
      " Graphic Design Studio 3 ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Infographics Studio ",
      " Branding ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Landscape Architecture",
    "core": [
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Site Tectonics ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Mechanical Systems",
    "core": [
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Systems Design ",
      " Systems Modelling and Analysis ",
    ],
  },
  {
    "name": "Performance Design",
    "core": [
      " Performance Design Studio ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Property",
    "core": [
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      "",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      "",
      " Sound in Performance ",
      "",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  {
    "name": "Spatial Systems",
    "core": [
      " Engineering Risk Analysis ",
      " Imaging the Environment ",
      " Integrated Spatial Systems ",
      " Land Administration Systems ",
    ],
  },
  {
    "name": "Urban Planning",
    "core": [
      " Urban Precinct Studio ",
      " Planning Scenario and Policy Workshop ",
      " Research Methods for Planners ",
      " Global Foundations of Design ",
      " Understanding the Built Environment ",
      " Foundations of Design: Representation ",
      " Construction as Alchemy ",
      " Design Studio Alpha ",
      " Economics and Cities ",
      " Introduction to Urban Planning ",
      " Principles of Building ",
      " Natural History ",
      " Design Studio Beta ",
      " Design Studio Gamma ",
      " Modern Architecture: MoMo to PoMo ",
      " Digital Design ",
      " Construction Analysis ",
      " Cities: From Local to Global ",
      " Environmental Building Systems ",
      " Design and Property Industry Studies ",
      " Construction of Residential Buildings ",
      " Construction of Concrete Buildings ",
      " Measurement of Building Designs ",
      " Finance for Built Environment ",
      " Design and Property Principles ",
      " Design and Property Industry Studies ",
      " Design Studio Delta ",
      " Design Studio Epsilon ",
      " Construction Design ",
      " Landscape Studio: Urban Open Space ",
      " Landscape Studio: Designed Ecologies ",
      " Construction Contract Administration ",
      " Industry Partner project Studio ",
      " Steel and Concrete Structural Systems ",
      " Construction Management ",
      " Planning Scenario and Policy Workshop ",
      " Urban Precinct Studio ",
      " Property Case Studies ",
      " Valuation of Land and Buildings ",
      " Sustainable Management of Design Assets ",
      " Design and Property Studio ",
      " Cities Past and Future ",
      " Designing Living Systems ",
      " Urban Design for People and Places ",
      " Calculus 1 ",
      " Calculus 2 ",
      " Linear Algebra ",
      " Engineering Mathematics ",
      " Physics 1 ",
      " Foundations of Algorithms ",
      " Media Computation ",
      " Fundamentals of Interaction Design ",
      " Statics ",
      " Engineering Mechanics ",
      " Earth Processes for Engineering ",
      " Engineering Materials ",
      " Foundations of Electrical Networks ",
      " Applications of GIS ",
      " Surveying and Mapping ",
      " Database Systems ",
      " Design of Algorithms ",
      " Elements of Data Processing ",
      " Engineering Computation ",
      " Engineering Risk Analysis ",
      " Structural Theory and Design ",
      " Systems Modelling and Design ",
      " Fluid Mechanics ",
      " Mechanics  Materials ",
      " Thermodynamics and Fluid Mechanics ",
      " Mechanical Design ",
      " Imaging the Environment ",
      " Land Administration Systems ",
      " Integrated Spatial Systems ",
      " Web Information Technologies ",
      " Graphics and Interaction ",
      " Computer Systems ",
      " IT Project ",
      " Engineering Mathematics ",
      " Usability Evaluation Methods ",
      " Interactive Technology Project ",
      " Mapping Environments ",
      " Game Design ",
      " Critical and Theoretical Studies 1 ",
      " Critical and Theoretical Studies 2 ",
      " Critical and Theoretical Studies 3 ",
      " Graphic Design Studio 11: Image  Text ",
      " Graphic Design Studio 22: Image  Media ",
      " Colour Studio ",
      " Photomedia Studio ",
      " The Power of Text and Image ",
      " Graphic Design Studio 3 ",
      " Sound in Performance ",
      " The Figure in Performance ",
      " Light Studio ",
      " Light in Performance ",
      " Space Studio ",
      " Space in Performance ",
      " Performance Design Studio ",
      " Transit Oriented Development ",
      " Principles of Marketing ",
      " Principles of Business Law ",
    ],
  },
  { "name": "Ancient World Studies", "core": [] },
  { "name": "Anthropology", "core": [] },
  { "name": "Arabic Studies", "core": [] },
  { "name": "Art History", "core": [] },
  { "name": "Asian Studies", "core": [] },
  { "name": "Chinese Studies", "core": [] },
  { "name": "Classics", "core": [] },
  { "name": "Creative Writing", "core": [] },
  { "name": "Criminology", "core": [] },
  { "name": "Economics", "core": [] },
  { "name": "English and Theatre Studies", "core": [] },
  { "name": "French Studies", "core": [] },
  { "name": "Gender Studies", "core": [] },
  {
    "name": "Geography",
    "core": [
      " Global Climate Change in Context ",
      " Biogeography and Ecology of Fire ",
      " China Field Class ",
      " East Timor Field Class ",
      " Local Sites, Global Connections ",
      " Arid Australia Field Class ",
      " Geomorphology: Catchment to Coast ",
      " Sustainable Development ",
      " The Disaster Resilient City ",
      " Riverine Landscapes: Hydrology  Ecology ",
      " Africa: Environment, Development, People ",
      " Spatial Modelling for Nature and People ",
    ],
  },
  {
    "name": "German Studies",
    "core": [
      " German 7 ",
      " German 8 ",
      " German 9 ",
      " German 1100 ",
      " German Cultural Studies  ",
    ],
  },
  { "name": "Hebrew and Jewish Studies", "core": [] },
  { "name": "History", "core": [] },
  { "name": "History and Philosophy of Science", "core": [] },
  { "name": "Indigenous Studies", "core": [] },
  { "name": "Indonesian Studies", "core": [" Indonesian 5 ", " Indonesian 6 "] },
  { "name": "Islamic Studies", "core": [] },
  {
    "name": "Italian Studies",
    "core": [
      " Italian 5 ",
      " Italian 6 ",
      " Italian 7 ",
      " Italian 8 ",
      " Italian Cultural Studies  ",
      " Italian 7 ",
      " Italian 8 ",
    ],
  },
  { "name": "Japanese Studies", "core": [] },
  { "name": "Linguistics and Applied Linguistics", "core": [] },
  { "name": "Media and Communications", "core": [] },
  { "name": "Philosophy", "core": [] },
  { "name": "Politics and International Studies", "core": [] },
  {
    "name": "Psychology",
    "core": [
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
      " Research Methods for Human Inquiry ",
      " Psychological Science: Theory  Practice ",
      " The Unconscious Mind ",
      " Lifespan Social  Emotional Development ",
      " Perception, Memory and Cognition ",
      " Neuroscience and the Mind ",
      " The Psychopathology of Everyday Life ",
      " Development of the Thinking Child ",
      " The Integrated Brain ",
      " Trends in Personality& Social Psychology ",
    ],
  },
  { "name": "Russian Studies", "core": [] },
  { "name": "Screen and Cultural Studies", "core": [] },
  { "name": "Sociology", "core": [] },
  { "name": "Spanish and Latin American Studies", "core": [] },
];
