export const majors = [
    { "name": "Agricultural Science", "core": [
{ "name":  "Agricultural Systems Analysis"  },
{ "name":  "Livestock Production Systems"  },
{ "name":  "Plant Pathology"  },
{ "name":  "Irrigation and Water Management"  },
{ "name":  "Soil Management"  },
{ "name":  "Managing Production Animal Health"  },
{ "name":  "Applications in Precision Agriculture"  },
]},
{ "name": "Animal Health and Disease", "core": [
{ "name":  "Animal Disease Biotechnology 1"  },
{ "name":  "Animal Disease Biotechnology 2"  },
{ "name":  "Production Animal Health"  },
{ "name":  "Health  Disease in Wildlife Populations"  },
]},
{ "name": "Animal Science and Management", "core": [
{ "name":  "Animal Systems Analysis"  },
{ "name":  "Applied Animal Behaviour"  },
{ "name":  "Livestock Production Systems"  },
{ "name":  "Animal Disease Biotechnology 1"  },
{ "name":  "Animal Disease Biotechnology 2"  },
{ "name":  "Applied Animal Reproduction  Genetics"  },
{ "name":  "Production Animal Physiology"  },
{ "name":  "Production Animal Health"  },
{ "name":  "Managing Production Animal Health"  },
{ "name":  "Applications in Precision Agriculture"  },
]},
{ "name": "Biochemistry and Molecular Biology", "core": [
{ "name":  "Protein Structure and Function"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Cellular Metabolism and Disease"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Medical Microbiology: Parasitology"  },
]},
{ "name": "Bioengineering Systems", "core": [
{ "name":  "Biosystems Design"  },
{ "name":  "Introduction to Biomaterials"  },
{ "name":  "Introduction to Biomaterials"  },
]},
{ "name": "Biotechnology", "core": [
{ "name":  "Trends  Issues in Agrifood Biotech"  },
{ "name":  "Functional Foods"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Animal Disease Biotechnology 1"  },
{ "name":  "Animal Disease Biotechnology 2"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Advanced Techniques in Molecular Science"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Techniques in Immunology"  },
{ "name":  "Techniques in Microbiology"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Drugs in Biomedical Experiments"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Drugs: From Discovery to Market"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Developmental Biology"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Plant Molecular Biology  Biotechnology"  },
{ "name":  "Stem Cells in Development  Regeneration"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Evolutionary Genetics and Genomics"  },
{ "name":  "Genetic Analysis"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Reactivity and Mechanism"  },
{ "name":  "Analytical  Environmental Chemistry"  },
{ "name":  "Specialised Topics in Chemistry "  },
{ "name":  "Specialised Topics in Chemistry "  },
]},
{ "name": "Cell and Developmental Biology", "core": [
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Mechanisms of Human Disease"  },
]},
{ "name": "Chemical Systems", "core": [
{ "name":  "Reactor Engineering"  },
{ "name":  "Heat and Mass Transport Processes"  },
{ "name":  "Safety and Sustainability Case Studies"  },
{ "name":  "Fluid Mechanics"  },
]},
{ "name": "Chemistry", "core": [
{ "name":  "Advanced Practical Chemistry"  },
{ "name":  "Reactivity and Mechanism"  },
{ "name":  "Specialised Topics in Chemistry "  },
{ "name":  "Specialised Topics in Chemistry "  },
{ "name":  "Analytical  Environmental Chemistry"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Physics 11: Fundamentals"  },
{ "name":  "Reactivity and Mechanism"  },
{ "name":  "Advanced Practical Chemistry"  },
{ "name":  "Drugs: From Discovery to Market"  },
{ "name":  "Drugs in Biomedical Experiments"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Physics 11: Fundamentals"  },
]},
{ "name": "Civil Systems", "core": [
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Fluid Mechanics"  },
]},
{ "name": "Climate and Weather", "core": [
{ "name":  "Dynamical Meteorology and Oceanography"  },
{ "name":  "Modern and Future Climate"  },
{ "name":  "Atmosphere Ocean Interaction"  },
{ "name":  "Atmospheric Processes and Composition"  },
]},
{ "name": "Computational Biology", "core": [
{ "name":  "Biological Modelling and Simulation"  },
{ "name":  "Case Studies In Computational Biology"  },
{ "name":  "Statistical Genomics"  },
]},
{ "name": "Computing and Software Systems", "core": [
{ "name":  "Software Modelling and Design"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Models of Computation"  },
]},
{ "name": "Data Science", "core": [
{ "name":  "Machine Learning"  },
{ "name":  "Linear Statistical Models"  },
{ "name":  "Modern Applied Statistics"  },
{ "name":  "Applied Data Science"  },
]},
{ "name": "Ecology and Evolutionary Biology", "core": [
{ "name":  "Ecology in Changing Environments"  },
]},
{ "name": "Ecosystem Science", "core": [
{ "name":  "Landscape Ecosystem Project"  },
{ "name":  "Green Infrastructure Technologies"  },
{ "name":  "Urban Forest Ecosystems"  },
{ "name":  "Ecology of Urban Landscapes"  },
{ "name":  "Landscape Ecosystem Project"  },
{ "name":  "Forest Systems"  },
{ "name":  "Vegetation Management and Conservation"  },
{ "name":  "Field Botany"  },
{ "name":  "Applied Ecology"  },
{ "name":  "Environmental Risk Assessment"  },
{ "name":  "Urban Forest Ecosystems"  },
{ "name":  "Nature, Conservation and Society"  },
]},
{ "name": "Electrical Systems", "core": [
{ "name":  "Electrical Network Analysis and Design"  },
{ "name":  "Electrical Device Modelling"  },
{ "name":  "Signals and Systems"  },
{ "name":  "Electronic System Implementation"  },
]},
{ "name": "Environmental Engineering Systems", "core": [
{ "name":  "Fluid Mechanics"  },
{ "name":  "Biotransport Processes"  },
{ "name":  "Environmental Eng Systems Capstone"  },
{ "name":  "Systems Modelling and Design"  },
]},
{ "name": "Environmental Science", "core": [
{ "name":  "Environmental Risk Assessment"  },
{ "name":  "Problem Solving in Environmental Science"  },
{ "name":  "Vegetation Management and Conservation"  },
{ "name":  "Applied Ecology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Marine Ecosystems: Ecology  Management"  },
{ "name":  "Green Infrastructure Technologies"  },
{ "name":  "Ecology of Urban Landscapes"  },
{ "name":  "Landscape Ecosystem Project"  },
{ "name":  "Forest Systems"  },
{ "name":  "Urban Forest Ecosystems"  },
{ "name":  "Riverine Landscapes: Hydrology  Ecology"  },
{ "name":  "Biogeography and Ecology of Fire"  },
{ "name":  "Geobiology: Fossils  Environments"  },
{ "name":  "Environmental Risk Assessment"  },
{ "name":  "Problem Solving in Environmental Science"  },
{ "name":  "Atmospheric Processes and Composition"  },
{ "name":  "Analytical  Environmental Chemistry"  },
{ "name":  "Hydrogeology/Environmental Geochemistry"  },
{ "name":  "Landscape Ecosystem Project"  },
{ "name":  "Geomorphology: Catchment to Coast"  },
{ "name":  "Tectonics  Geodynamics"  },
{ "name":  "Sedimentary Geology"  },
{ "name":  "Applied Geophysics"  },
{ "name":  "Geobiology: Fossils  Environments"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "The Disaster Resilient City"  },
{ "name":  "Environmental Risk Assessment"  },
{ "name":  "Problem Solving in Environmental Science"  },
{ "name":  "Dynamical Meteorology and Oceanography"  },
{ "name":  "Atmosphere Ocean Interaction"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Global Climate Change in Context"  },
{ "name":  "Environmental Risk Assessment"  },
{ "name":  "Problem Solving in Environmental Science"  },
{ "name":  "Nature, Conservation and Society"  },
{ "name":  "Sustainable Development"  },
]},
{ "name": "Food Science", "core": [
{ "name":  "Advanced Food Analysis"  },
{ "name":  "Food Processing  Preservation"  },
{ "name":  "Food Research  Development"  },
{ "name":  "Functional Foods"  },
]},
{ "name": "Forest Science", "core": [
]},
{ "name": "Genetics", "core": [
{ "name":  "Evolutionary Genetics and Genomics"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Genetic Analysis"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Evolution and the Human Condition"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Plant Evolution"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Human and Medical Genetics"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Science Research Project"  },
{ "name":  "Science and Technology Internship"  },
]},
{ "name": "Geography", "core": [
{ "name":  "Global Climate Change in Context"  },
{ "name":  "Biogeography and Ecology of Fire"  },
{ "name":  "China Field Class"  },
{ "name":  "East Timor Field Class"  },
{ "name":  "Local Sites, Global Connections"  },
{ "name":  "Arid Australia Field Class"  },
{ "name":  "Geomorphology: Catchment to Coast"  },
{ "name":  "Sustainable Development"  },
{ "name":  "The Disaster Resilient City"  },
{ "name":  "Riverine Landscapes: Hydrology  Ecology"  },
{ "name":  "Africa: Environment, Development, People"  },
{ "name":  "Spatial Modelling for Nature and People"  },
]},
{ "name": "Geology", "core": [
{ "name":  "Tectonics  Geodynamics"  },
{ "name":  "Sedimentary Geology"  },
{ "name":  "Hydrogeology/Environmental Geochemistry"  },
{ "name":  "Geochemistry  Petrogenesis"  },
{ "name":  "Applied Geophysics"  },
{ "name":  "Economic Geology"  },
{ "name":  "Advanced Field Geology"  },
{ "name":  "Science Research Project"  },
{ "name":  "Geobiology: Fossils  Environments"  },
]},
{ "name": "Human Nutrition", "core": [
{ "name":  "Advanced Topics in Nutrition"  },
{ "name":  "Monitoring Food and Nutrition Intake"  },
{ "name":  "Lifestage Nutrition"  },
{ "name":  "Molecular Nutrition and Genomics"  },
{ "name":  "Cellular Metabolism and Disease"  },
]},
{ "name": "Human Structure and Function", "core": [
{ "name":  "Human Locomotor Systems"  },
{ "name":  "Viscera and Visceral Systems"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Developmental Biology"  },
{ "name":  "Visual Neuroscience"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Techniques for Investigation of Disease"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Advanced Human Physiology"  },
{ "name":  "Clinical and Translational Physiology"  },
{ "name":  "Physiology: Adapting to Challenges"  },
]},
{ "name": "Immunology", "core": [
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical and Applied Immunology"  },
{ "name":  "Techniques in Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Medical Microbiology: Parasitology"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Cellular Metabolism and Disease"  },
{ "name":  "Drug Treatment of Disease"  },
]},
{ "name": "Infection and Immunity", "core": [
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Medical Microbiology: Parasitology"  },
]},
{ "name": "Informatics", "core": [
]},
{ "name": "Marine Biology", "core": [
{ "name":  "Marine Botany"  },
{ "name":  "Marine Ecosystems: Ecology  Management"  },
{ "name":  "Experimental Marine Biology"  },
{ "name":  "Analytical  Environmental Chemistry"  },
{ "name":  "Applied Ecology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Geomorphology: Catchment to Coast"  },
{ "name":  "Imaging the Environment"  },
]},
{ "name": "Mathematical Physics", "core": [
{ "name":  "Quantum Physics"  },
{ "name":  "Complex Analysis"  },
]},
{ "name": "Mathematics and Statistics", "core": [
{ "name":  "Complex Analysis"  },
{ "name":  "Metric and Hilbert Spaces"  },
{ "name":  "Algebra"  },
{ "name":  "Graph Theory"  },
{ "name":  "Discrete Mathematics"  },
{ "name":  "Geometry"  },
{ "name":  "Complex Analysis"  },
{ "name":  "Numerical Methods  Scientific Computing"  },
{ "name":  "Stochastic Modelling"  },
{ "name":  "Applied Mathematical Modelling"  },
{ "name":  "Methods of Mathematical Physics"  },
{ "name":  "Discrete Mathematics"  },
{ "name":  "Techniques in Operations Research"  },
{ "name":  "Complex Analysis"  },
{ "name":  "Stochastic Modelling"  },
{ "name":  "Graph Theory"  },
{ "name":  "Decision Making"  },
{ "name":  "Linear Statistical Models"  },
{ "name":  "Linear Statistical Models"  },
{ "name":  "Stochastic Modelling"  },
{ "name":  "Probability for Inference"  },
{ "name":  "Modern Applied Statistics"  },
]},
{ "name": "Mechanical Systems", "core": [
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Systems Design"  },
{ "name":  "Systems Modelling and Analysis"  },
]},
{ "name": "Mechatronics Systems", "core": [
{ "name":  "Analog and Digital Electronics Concepts"  },
{ "name":  "Numerical Algorithms in Engineering"  },
{ "name":  "Systems Modelling and Analysis"  },
{ "name":  "Mechanical Systems Design"  },
]},
{ "name": "Microbiology", "core": [
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Medical Microbiology: Parasitology"  },
{ "name":  "Techniques in Microbiology"  },
]},
{ "name": "Neuroscience", "core": [
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Complex Functions in Neuroscience"  },
{ "name":  "Visual Neuroscience"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Real and Artificial Neural Networks"  },
{ "name":  "Auditory Neuroscience"  },
]},
{ "name": "Pathology", "core": [
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Techniques for Investigation of Disease"  },
{ "name":  "Frontiers in Human Disease"  },
{ "name":  "Advanced Investigation of Human Disease"  },
{ "name":  "Biomedical Science Research Project"  },
]},
{ "name": "Pharmacology", "core": [
{ "name":  "Drugs in Biomedical Experiments"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Drugs: From Discovery to Market"  },
]},
{ "name": "Physics", "core": [
{ "name":  "Quantum Physics"  },
{ "name":  "Reactivity and Mechanism"  },
{ "name":  "Electrodynamics"  },
{ "name":  "Statistical Physics"  },
{ "name":  "Quantum Physics"  },
{ "name":  "Laboratory and Computational Physics 3"  },
{ "name":  "Statistical Physics"  },
{ "name":  "Electrodynamics"  },
]},
{ "name": "Physiology", "core": [
{ "name":  "Advanced Human Physiology"  },
{ "name":  "Human Locomotor Systems"  },
{ "name":  "Viscera and Visceral Systems"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Complex Functions in Neuroscience"  },
{ "name":  "Experimental Physiology"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Clinical and Translational Physiology"  },
{ "name":  "Physiology: Adapting to Challenges"  },
]},
{ "name": "Plant Science", "core": [
{ "name":  "Plant Evolution"  },
{ "name":  "Marine Botany"  },
{ "name":  "Vegetation Management and Conservation"  },
{ "name":  "Plant Molecular Biology  Biotechnology"  },
{ "name":  "Field Botany"  },
{ "name":  "Science Research Project"  },
{ "name":  "Plant Pathology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Forest Systems"  },
]},
{ "name": "Psychology", "core": [
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
{ "name":  "Research Methods for Human Inquiry"  },
{ "name":  "Psychological Science: Theory  Practice"  },
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
]},
{ "name": "Spatial Systems", "core": [
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Land Administration Systems"  },
]},
{ "name": "Veterinary BioSciences", "core": [
{ "name":  "Veterinary Bioscience:Respiratory System"  },
{ "name":  "Veterinary Bioscience: Cells to Systems"  },
{ "name":  "Animal Production Systems 2"  },
{ "name":  "Introduction to Professional Practice"  },
{ "name":  "Animal Production Systems 1"  },
{ "name":  "Veterinary Bioscience: Cardiovasc System"  },
{ "name":  "Veterinary Bioscience: Digestive System"  },
{ "name":  "Veterinary Bioscience: Metabolism"  },
]},
{ "name": "Zoology", "core": [
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Experimental Animal Behaviour"  },
{ "name":  "Experimental Marine Biology"  },
{ "name":  "Tropical Field Ecology"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Developmental Biology"  },
{ "name":  "Applied Ecology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Marine Ecosystems: Ecology  Management"  },
{ "name":  "Evolutionary Genetics and Genomics"  },
{ "name":  "Science Research Project"  },
{ "name":  "Evolution and the Human Condition"  },
{ "name":  "Animal Behaviour"  },
{ "name":  "Experimental Animal Behaviour"  },
{ "name":  "Experimental Marine Biology"  },
{ "name":  "Tropical Field Ecology"  },
]},
{ "name": "Accounting", "core": [
{ "name":  "Accounting Reports and Analysis"  },
{ "name":  "Introductory Financial Accounting"  },
{ "name":  "Cost Management"  },
{ "name":  "Intermediate Financial Accounting"  },
{ "name":  "Accounting Information: Risks  Controls"  },
]},
{ "name": "Actuarial Studies", "core": [
{ "name":  "Introductory Financial Mathematics"  },
{ "name":  "Stochastic Techniques in Insurance"  },
{ "name":  "Topics in Actuarial Studies"  },
{ "name":  "Actuarial Modelling "  },
{ "name":  "Actuarial Modelling II"  },
{ "name":  "Contingencies"  },
{ "name":  "Actuarial Statistics"  },
{ "name":  "Intermediate Financial Mathematics"  },
{ "name":  "Actuarial Modelling III"  },
{ "name":  "Actuarial Analytics and Data "  },
]},
{ "name": "Economics", "core": [
]},
{ "name": "Finance", "core": [
{ "name":  "Investments"  },
{ "name":  "Derivative Securities"  },
{ "name":  "Entrepreneurial Finance"  },
{ "name":  "Street Finance"  },
{ "name":  "Ethics in Finance"  },
{ "name":  "Algorithmic Trading"  },
{ "name":  "Essentials of Corporate Valuation"  },
{ "name":  "Foundations of FinTech"  },
]},
{ "name": "Management", "core": [
{ "name":  "Business Judgement"  },
{ "name":  "Managing Globally"  },
{ "name":  "Managing Entrepreneurship and Innovation"  },
{ "name":  "Managing Supply Chain Networks"  },
{ "name":  "Management Consulting"  },
{ "name":  "Managing for Competitive Advantage"  },
{ "name":  "Managing Work and Your Career"  },
{ "name":  "Global Management Consulting"  },
{ "name":  "The Future of Work"  },
]},
{ "name": "Marketing", "core": [
{ "name":  "Business Judgement"  },
{ "name":  "Service and Relationship Marketing"  },
{ "name":  "Retailing"  },
{ "name":  "Digital Marketing"  },
{ "name":  "Advertising and Promotions"  },
{ "name":  "Product Management"  },
{ "name":  "Business and Marketing Ethics"  },
]},
{ "name": "Architecture", "core": [
{ "name":  "Construction Design"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Civil Systems", "core": [
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Fluid Mechanics"  },
]},
{ "name": "Computing", "core": [
{ "name":  "Web Information Technologies"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Construction", "core": [
{ "name":  "Construction Management"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Digital Technologies", "core": [
{ "name":  "Web Information Technologies"  },
{ "name":  "Game Design"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Graphic Design", "core": [
{ "name":  "Infographics Studio"  },
{ "name":  "Branding"  },
{ "name":  "Graphic Design Studio 3"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Infographics Studio"  },
{ "name":  "Branding"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Landscape Architecture", "core": [
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Site Tectonics"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Mechanical Systems", "core": [
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Systems Design"  },
{ "name":  "Systems Modelling and Analysis"  },
]},
{ "name": "Performance Design", "core": [
{ "name":  "Performance Design Studio"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Property", "core": [
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },

{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },

{ "name":  "Sound in Performance"  },

{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Spatial Systems", "core": [
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Land Administration Systems"  },
]},
{ "name": "Urban Planning", "core": [
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Research Methods for Planners"  },
{ "name":  "Global Foundations of Design"  },
{ "name":  "Understanding the Built Environment"  },
{ "name":  "Foundations of Design: Representation"  },
{ "name":  "Construction as Alchemy"  },
{ "name":  "Design Studio Alpha"  },
{ "name":  "Economics and Cities"  },
{ "name":  "Introduction to Urban Planning"  },
{ "name":  "Principles of Building"  },
{ "name":  "Natural History"  },
{ "name":  "Design Studio Beta"  },
{ "name":  "Design Studio Gamma"  },
{ "name":  "Modern Architecture: MoMo to PoMo"  },
{ "name":  "Digital Design"  },
{ "name":  "Construction Analysis"  },
{ "name":  "Cities: From Local to Global"  },
{ "name":  "Environmental Building Systems"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Construction of Residential Buildings"  },
{ "name":  "Construction of Concrete Buildings"  },
{ "name":  "Measurement of Building Designs"  },
{ "name":  "Finance for Built Environment"  },
{ "name":  "Design and Property Principles"  },
{ "name":  "Design and Property Industry Studies"  },
{ "name":  "Design Studio Delta"  },
{ "name":  "Design Studio Epsilon"  },
{ "name":  "Construction Design"  },
{ "name":  "Landscape Studio: Urban Open Space"  },
{ "name":  "Landscape Studio: Designed Ecologies"  },
{ "name":  "Construction Contract Administration"  },
{ "name":  "Industry Partner project Studio"  },
{ "name":  "Steel and Concrete Structural Systems"  },
{ "name":  "Construction Management"  },
{ "name":  "Planning Scenario and Policy Workshop"  },
{ "name":  "Urban Precinct Studio"  },
{ "name":  "Property Case Studies"  },
{ "name":  "Valuation of Land and Buildings"  },
{ "name":  "Sustainable Management of Design Assets"  },
{ "name":  "Design and Property Studio"  },
{ "name":  "Cities Past and Future"  },
{ "name":  "Designing Living Systems"  },
{ "name":  "Urban Design for People and Places"  },
{ "name":  "Calculus 1"  },
{ "name":  "Calculus 2"  },
{ "name":  "Linear Algebra"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Physics 1"  },
{ "name":  "Foundations of Algorithms"  },
{ "name":  "Media Computation"  },
{ "name":  "Fundamentals of Interaction Design"  },
{ "name":  "Statics"  },
{ "name":  "Engineering Mechanics"  },
{ "name":  "Earth Processes for Engineering"  },
{ "name":  "Engineering Materials"  },
{ "name":  "Foundations of Electrical Networks"  },
{ "name":  "Applications of GIS"  },
{ "name":  "Surveying and Mapping"  },
{ "name":  "Database Systems"  },
{ "name":  "Design of Algorithms"  },
{ "name":  "Elements of Data Processing"  },
{ "name":  "Engineering Computation"  },
{ "name":  "Engineering Risk Analysis"  },
{ "name":  "Structural Theory and Design"  },
{ "name":  "Systems Modelling and Design"  },
{ "name":  "Fluid Mechanics"  },
{ "name":  "Mechanics  Materials"  },
{ "name":  "Thermodynamics and Fluid Mechanics"  },
{ "name":  "Mechanical Design"  },
{ "name":  "Imaging the Environment"  },
{ "name":  "Land Administration Systems"  },
{ "name":  "Integrated Spatial Systems"  },
{ "name":  "Web Information Technologies"  },
{ "name":  "Graphics and Interaction"  },
{ "name":  "Computer Systems"  },
{ "name":  "IT Project"  },
{ "name":  "Engineering Mathematics"  },
{ "name":  "Usability Evaluation Methods"  },
{ "name":  "Interactive Technology Project"  },
{ "name":  "Mapping Environments"  },
{ "name":  "Game Design"  },
{ "name":  "Critical and Theoretical Studies 1"  },
{ "name":  "Critical and Theoretical Studies 2"  },
{ "name":  "Critical and Theoretical Studies 3"  },
{ "name":  "Graphic Design Studio 11: Image  Text"  },
{ "name":  "Graphic Design Studio 22: Image  Media"  },
{ "name":  "Colour Studio"  },
{ "name":  "Photomedia Studio"  },
{ "name":  "The Power of Text and Image"  },
{ "name":  "Graphic Design Studio 3"  },
{ "name":  "Sound in Performance"  },
{ "name":  "The Figure in Performance"  },
{ "name":  "Light Studio"  },
{ "name":  "Light in Performance"  },
{ "name":  "Space Studio"  },
{ "name":  "Space in Performance"  },
{ "name":  "Performance Design Studio"  },
{ "name":  "Transit Oriented Development"  },
{ "name":  "Principles of Marketing"  },
{ "name":  "Principles of Business Law"  },
]},
{ "name": "Biochemistry and Molecular Biology", "core": [

{ "name":  "Protein Structure and Function"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Cellular Metabolism and Disease"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Medical Microbiology: Parasitology"  },
]},
{ "name": "Bioengineering Systems", "core": [
{ "name":  "Biosystems Design"  },
{ "name":  "Introduction to Biomaterials"  },
{ "name":  "Introduction to Biomaterials"  },
]},
{ "name": "Biotechnology", "core": [
{ "name":  "Trends  Issues in Agrifood Biotech"  },
{ "name":  "Functional Foods"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Animal Disease Biotechnology 1"  },
{ "name":  "Animal Disease Biotechnology 2"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Advanced Techniques in Molecular Science"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Techniques in Immunology"  },
{ "name":  "Techniques in Microbiology"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Drugs in Biomedical Experiments"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Drugs: From Discovery to Market"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Developmental Biology"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Plant Molecular Biology  Biotechnology"  },
{ "name":  "Stem Cells in Development  Regeneration"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Evolutionary Genetics and Genomics"  },
{ "name":  "Genetic Analysis"  },
{ "name":  "Biotechnology in Practice"  },
{ "name":  "Reactivity and Mechanism"  },
{ "name":  "Analytical  Environmental Chemistry"  },
{ "name":  "Specialised Topics in Chemistry "  },
{ "name":  "Specialised Topics in Chemistry "  },
]},
{ "name": "Cell and Developmental Biology", "core": [
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Experimental Reproductive Physiology"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Mechanisms of Human Disease"  },
]},
{ "name": "Genetics", "core": [
{ "name":  "Evolutionary Genetics and Genomics"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Genetic Analysis"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Ecology in Changing Environments"  },
{ "name":  "Evolution and the Human Condition"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Plant Evolution"  },
{ "name":  "Principles of Immunology"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Human and Medical Genetics"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Science Research Project"  },
{ "name":  "Science and Technology Internship"  },
]},
{ "name": "Human Nutrition", "core": [
{ "name":  "Advanced Topics in Nutrition"  },
{ "name":  "Monitoring Food and Nutrition Intake"  },
{ "name":  "Lifestage Nutrition"  },
{ "name":  "Molecular Nutrition and Genomics"  },
{ "name":  "Cellular Metabolism and Disease"  },
]},
{ "name": "Human Structure and Function", "core": [
{ "name":  "Human Locomotor Systems"  },
{ "name":  "Viscera and Visceral Systems"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Developmental Biology"  },
{ "name":  "Visual Neuroscience"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Techniques for Investigation of Disease"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Advanced Human Physiology"  },
{ "name":  "Clinical and Translational Physiology"  },
{ "name":  "Physiology: Adapting to Challenges"  },
]},
{ "name": "Immunology", "core": [
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical and Applied Immunology"  },
{ "name":  "Techniques in Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Protein Structure and Function"  },
{ "name":  "Functional Genomics and Bioinformatics"  },
{ "name":  "Molecular Aspects of Cell Biology"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Genes: Organisation and Function"  },
{ "name":  "Concepts in Cell  Developmental Biology"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Medical Microbiology: Parasitology"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Cellular Metabolism and Disease"  },
{ "name":  "Drug Treatment of Disease"  },
]},
{ "name": "Infection and Immunity", "core": [
{ "name":  "Principles of Immunology"  },
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Medical Microbiology: Parasitology"  },
]},
{ "name": "Microbiology", "core": [
{ "name":  "Medical Microbiology: Bacteriology"  },
{ "name":  "Medical Microbiology: Virology"  },
{ "name":  "Medical Microbiology: Parasitology"  },
{ "name":  "Techniques in Microbiology"  },
]},
{ "name": "Neuroscience", "core": [
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Developmental Neurobiology"  },
{ "name":  "Complex Functions in Neuroscience"  },
{ "name":  "Visual Neuroscience"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Cell Signalling and Neurochemistry"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Real and Artificial Neural Networks"  },
{ "name":  "Auditory Neuroscience"  },
]},
{ "name": "Pathology", "core": [
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Techniques for Investigation of Disease"  },
{ "name":  "Frontiers in Human Disease"  },
{ "name":  "Advanced Investigation of Human Disease"  },
{ "name":  "Biomedical Science Research Project"  },
]},
{ "name": "Pharmacology", "core": [
{ "name":  "Drugs in Biomedical Experiments"  },
{ "name":  "Drugs Affecting the Nervous System"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Drugs: From Discovery to Market"  },
]},
{ "name": "Physiology", "core": [
{ "name":  "Advanced Human Physiology"  },
{ "name":  "Human Locomotor Systems"  },
{ "name":  "Viscera and Visceral Systems"  },
{ "name":  "Reproductive Physiology"  },
{ "name":  "Neurophysiology: Neurons and Circuits"  },
{ "name":  "Principles of Neuroscience"  },
{ "name":  "Complex Functions in Neuroscience"  },
{ "name":  "Experimental Physiology"  },
{ "name":  "Biomedical Science Research Project"  },
{ "name":  "Mechanisms of Human Disease"  },
{ "name":  "Drug Treatment of Disease"  },
{ "name":  "Clinical and Translational Physiology"  },
{ "name":  "Physiology: Adapting to Challenges"  },
]},
{ "name": "Psychology", "core": [
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
{ "name":  "Research Methods for Human Inquiry"  },
{ "name":  "Psychological Science: Theory  Practice"  },
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
]},
{ "name": "Ancient World Studies", "core": [
]},
{ "name": "Anthropology", "core": [
]},
{ "name": "Arabic Studies", "core": [
]},
{ "name": "Art History", "core": [
]},
{ "name": "Asian Studies", "core": [
]},
{ "name": "Chinese Studies", "core": [
]},
{ "name": "Classics", "core": [
]},
{ "name": "Creative Writing", "core": [
]},
{ "name": "Criminology", "core": [
]},
{ "name": "Economics", "core": [
]},
{ "name": "English and Theatre Studies", "core": [
]},
{ "name": "French Studies", "core": [
]},
{ "name": "Gender Studies", "core": [
]},
{ "name": "Geography", "core": [
{ "name":  "Global Climate Change in Context"  },
{ "name":  "Biogeography and Ecology of Fire"  },
{ "name":  "China Field Class"  },
{ "name":  "East Timor Field Class"  },
{ "name":  "Local Sites, Global Connections"  },
{ "name":  "Arid Australia Field Class"  },
{ "name":  "Geomorphology: Catchment to Coast"  },
{ "name":  "Sustainable Development"  },
{ "name":  "The Disaster Resilient City"  },
{ "name":  "Riverine Landscapes: Hydrology  Ecology"  },
{ "name":  "Africa: Environment, Development, People"  },
{ "name":  "Spatial Modelling for Nature and People"  },
]},
{ "name": "German Studies", "core": [
{ "name":  "German 7"  },
{ "name":  "German 8"  },
{ "name":  "German 9"  },
{ "name":  "German 1100"  },
{ "name":  "German Cultural Studies "  },
]},
{ "name": "Hebrew and Jewish Studies", "core": [
]},
{ "name": "History", "core": [
]},
{ "name": "History and Philosophy of Science", "core": [
]},
{ "name": "Indigenous Studies", "core": [
]},
{ "name": "Indonesian Studies", "core": [
{ "name":  "Indonesian 5"  },
{ "name":  "Indonesian 6"  },
]},
{ "name": "Islamic Studies", "core": [
]},
{ "name": "Italian Studies", "core": [
{ "name":  "Italian 5"  },
{ "name":  "Italian 6"  },
{ "name":  "Italian 7"  },
{ "name":  "Italian 8"  },
{ "name":  "Italian Cultural Studies "  },
{ "name":  "Italian 7"  },
{ "name":  "Italian 8"  },
]},
{ "name": "Japanese Studies", "core": [
]},
{ "name": "Linguistics and Applied Linguistics", "core": [
]},
{ "name": "Media and Communications", "core": [
]},
{ "name": "Philosophy", "core": [
]},
{ "name": "Politics and International Studies", "core": [
]},
{ "name": "Psychology", "core": [
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
{ "name":  "Research Methods for Human Inquiry"  },
{ "name":  "Psychological Science: Theory  Practice"  },
{ "name":  "The Unconscious Mind"  },
{ "name":  "Lifespan Social  Emotional Development"  },
{ "name":  "Perception, Memory and Cognition"  },
{ "name":  "Neuroscience and the Mind"  },
{ "name":  "The Psychopathology of Everyday Life"  },
{ "name":  "Development of the Thinking Child"  },
{ "name":  "The Integrated Brain"  },
{ "name":  "Trends in Personality& Social Psychology"  },
]},
{ "name": "Russian Studies", "core": [
]},
{ "name": "Screen and Cultural Studies", "core": [
]},
{ "name": "Sociology", "core": [
]},
{ "name": "Spanish and Latin American Studies", "core": [
]}
]