Breadths  = [
{breadth_name: "Modern Chinese Literature"},
{breadth_name: "German 1"},
{breadth_name: "The Power and Limits of Logic"},
{breadth_name: "Memory & Memoirs of 20th Century Europe"},
{breadth_name: "Chinese 7"},
{breadth_name: "Life Drawing: The Body"},
{breadth_name: "Immigration in France"},
{breadth_name: "Arabic 6"},
{breadth_name: "Japanese Through Translation"},
{breadth_name: "Graphic Design Studio 3"},
{breadth_name: "Ethnic Nationalism and the Modern World"},
{breadth_name: "Chinese News Analysis"},
{breadth_name: "Literature: Reading Indonesian Lives"},
{breadth_name: "Grammar of English"},
{breadth_name: "Architecture Design Studio: Water"},
{breadth_name: "Europe and its Others"},
{breadth_name: "Music in Everyday Life"},
{breadth_name: "AI, Ethics and the Law"},
{breadth_name: "Research-Based Physiology"},
{breadth_name: "Exploring Latin America"},
{breadth_name: "Japanese 3"},
{breadth_name: "Astronomy in World History"},
{breadth_name: "Intensive Spanish 3 & 4"},
{breadth_name: "Indigenous Engineering and Design"},
{breadth_name: "Dancing the Dance 3: Dance for Video"},
{breadth_name: "Islam and Ethics: Doctrines and Debates"},
{breadth_name: "Transport Processes"},
{breadth_name: "The Foundations of Interpretation"},
{breadth_name: "Analysing Indonesia: Concepts and Issues"},
{breadth_name: "Physics 1"},
{breadth_name: "Advanced Recording Studio Techniques"},
{breadth_name: "German 7"},
{breadth_name: "Arabic 8"},
{breadth_name: "Poetry"},
{breadth_name: "The History of Children and Youth"},
{breadth_name: "Data Analysis 1"},
{breadth_name: "R&B, Soul & Gospel Choir"},
{breadth_name: "Italian 8"},
{breadth_name: "Spanish 6"},
{breadth_name: "French 5"},
{breadth_name: "Asia Pacific Modernities"},
{breadth_name: "String Ensemble 2"},
{breadth_name: "German 9"},
{breadth_name: "Arabic 5"},
{breadth_name: "Japanese 2"},
{breadth_name: "Plant Growth Processes"},
{breadth_name: "Ancient Egyptian 3"},
{breadth_name: "Spanish 1"},
{breadth_name: "Corruption in Asia"},
{breadth_name: "German 3"},
{breadth_name: "Pop-up Theatre: Performance in Community"},
{breadth_name: "The Ethics of Capitalism"},
{breadth_name: "Ecology of Urban Landscapes"},
{breadth_name: "Integrated Spatial Systems"},
{breadth_name: "Advanced Chinese Translation"},
{breadth_name: "Ancient & Contemporary Indigenous Arts 2"},
{breadth_name: "Intensive Beginners Latin"},
{breadth_name: "The Wellbeing Orchestra"},
{breadth_name: "The Making of Melbourne"},
{breadth_name: "French Translation"},
{breadth_name: "Making Music For Film And Animation 1"},
{breadth_name: "Managing Processes and Projects"},
{breadth_name: "University Symphonic Ensembles 1"},
{breadth_name: "Controversies in Australian History"},
{breadth_name: "Functional Foods"},
{breadth_name: "Contemporary Italy Study Abroad"},
{breadth_name: "Political Leadership"},
{breadth_name: "Racial Literacy: Indigeneity & Whiteness"},
{breadth_name: "Employment Law"},
{breadth_name: "Order, Disorder, Crime, Deviance"},
{breadth_name: "The Laptop Recording Studio"},
{breadth_name: "Animals in Society 1: Introduction"},
{breadth_name: "Consumer Behaviour"},
{breadth_name: "Accelerated Mathematics 2"},
{breadth_name: "Families, Relationships and Society"},
{breadth_name: "Russian 3"},
{breadth_name: "Japanese 5"},
{breadth_name: "Reading Japanese Literature"},
{breadth_name: "Genders and Desires in Asia"},
{breadth_name: "Lifestage Nutrition"},
{breadth_name: "Criminal Law and Political Justice"},
{breadth_name: "Pharmacology: How Drugs Work"},
{breadth_name: "Our Planet, Our Health II"},
{breadth_name: "Scripts for Contemporary Theatre"},
{breadth_name: "The House of Fiction: Literary Realism"},
{breadth_name: "Marine Botany"},
{breadth_name: "Arabic 2"},
{breadth_name: "Business Negotiations"},
{breadth_name: "History of Early Modern Philosophy"},
{breadth_name: "Baroque Ensemble 2"},
{breadth_name: "Graph Theory"},
{breadth_name: "German 8"},
{breadth_name: "Managing for Competitive Advantage"},
{breadth_name: "Electrical Network Analysis and Design"},
{breadth_name: "Managing Sustainably"},
{breadth_name: "Foundations of Algorithms"},
{breadth_name: "Diplomacy: Engaging the Muslim World"},
{breadth_name: "Arabic 3"},
{breadth_name: "Applied Animal Reproduction & Genetics"},
{breadth_name: "Human Rights in East and Southeast Asia"},
{breadth_name: "Understanding Masks"},
{breadth_name: "Principles of Management"},
{breadth_name: "Chinese in Context 2"},
{breadth_name: "Asian Religions in Societal Context"},
{breadth_name: "Indigenous Art and Changing the Nation"},
{breadth_name: "Europe: From Black Death to New Worlds"},
{breadth_name: "Making Movies 1"},
{breadth_name: "Measurement of Building Designs"},
{breadth_name: "The Ethnography of Music"},
{breadth_name: "Music Language 1: the Diatonic World"},
{breadth_name: "French 4"},
{breadth_name: "Indigenous Environmental Heritage"},
{breadth_name: "The Economics of Taxation"},
{breadth_name: "Applications in Precision Agriculture"},
{breadth_name: "Intermediate Microeconomics"},
{breadth_name: "Organisational Behaviour"},
{breadth_name: "The Artist's Toolbox"},
{breadth_name: "Advanced Seminar in Chinese"},
{breadth_name: "Ancient Greek 5"},
{breadth_name: "Vegetation Management and Conservation"},
{breadth_name: "French 3"},
{breadth_name: "Atmosphere Ocean Interaction"},
{breadth_name: "Actuarial Modelling I"},
{breadth_name: "Food Research & Development"},
{breadth_name: "German 6"},
{breadth_name: "Classical Mythology"},
{breadth_name: "Punishment and Social Control"},
{breadth_name: "Italian 5"},
{breadth_name: "Music and Film since 1900"},
{breadth_name: "Public Trials"},
{breadth_name: "German Cultural Studies C"},
{breadth_name: "Applied Geophysics"},
{breadth_name: "Climate Change: Why People Disagree"},
{breadth_name: "French 7"},
{breadth_name: "A History of Sexualities"},
{breadth_name: "Romanticism, Feminism, Revolution"},
{breadth_name: "Accounting for Corporate Entities"},
{breadth_name: "Dictators & Democrats: The Modern World"},
{breadth_name: "Declarative Programming"},
{breadth_name: "Engineering Risk Analysis"},
{breadth_name: "European Integration: Politics of the EU"},
{breadth_name: "Experimental Marine Biology"},
{breadth_name: "Hebrew 6"},
{breadth_name: "Chemistry 2"},
{breadth_name: "German 10"},
{breadth_name: "Cost Management"},
{breadth_name: "Object Oriented Software Development"},
{breadth_name: "Environmental Change & the Human Journey"},
{breadth_name: "Design and the Moving Image"},
{breadth_name: "China Since Mao"},
{breadth_name: "Greening Landscapes"},
{breadth_name: "Medical Microbiology: Virology"},
{breadth_name: "Foundations of Electrical Networks"},
{breadth_name: "Introduction to Climate Change"},
{breadth_name: "Music Language 3: Modern Directions"},
{breadth_name: "Korean 2"},
{breadth_name: "Hebrew 4"},
{breadth_name: "Agricultural Systems Analysis"},
{breadth_name: "Italian 6"},
{breadth_name: "Printing, Collage and Social Engagement"},
{breadth_name: "Under Camera Animation"},
{breadth_name: "Great Chinese Classics"},
{breadth_name: "Working with Value"},
{breadth_name: "European Renaissance Art"},
{breadth_name: "Race and Gender: Philosophical Issues"},
{breadth_name: "Italian Fictions"},
{breadth_name: "Novels"},
{breadth_name: "Contemporary Art"},
{breadth_name: "Spanish 2"},
{breadth_name: "Medical and Applied Immunology"},
{breadth_name: "Language and Society in Europe"},
{breadth_name: "Engineering Technology and Society"},
{breadth_name: "Real Analysis"},
{breadth_name: "Food Nutrition and Health"},
{breadth_name: "Links Between Health and Learning"},
{breadth_name: "Writing Videogames and Live Performance"},
{breadth_name: "Statistics"},
{breadth_name: "Design Studio Delta"},
{breadth_name: "Wonders Of The Weather"},
{breadth_name: "Making Movies 2"},
{breadth_name: "Entrepreneurial Finance"},
{breadth_name: "Structural Theory and Design"},
{breadth_name: "Social Theory and Political Analysis"},
{breadth_name: "Introduction to Screenprinting"},
{breadth_name: "From Page to Stage: French Theatre"},
{breadth_name: "Translation: Intercultural Indonesian"},
{breadth_name: "Logic: Language and Information"},
{breadth_name: "Service and Relationship Marketing"},
{breadth_name: "Psychoanalysis and Social Theory"},
{breadth_name: "Chinese 9"},
{breadth_name: "Natural Environments"},
{breadth_name: "Artificial Intelligence"},
{breadth_name: "Human and Medical Genetics"},
{breadth_name: "Sustainable Management of Design Assets"},
{breadth_name: "Anthropology of Gender and Sexuality"},
{breadth_name: "Lifespan Social & Emotional Development"},
{breadth_name: "Latin 4"},
{breadth_name: "Managing Supply Chain Networks"},
{breadth_name: "Graphics and Interaction"},
{breadth_name: "Software Modelling and Design"},
{breadth_name: "Spanish 3"},
{breadth_name: "Global Histories of Indigenous Activism"},
{breadth_name: "Introductory Biology: Life's Machinery"},
{breadth_name: "Animal Welfare and Ethics"},
{breadth_name: "Painting Techniques"},
{breadth_name: "Indonesian 5"},
{breadth_name: "Nature, Conservation and Society"},
{breadth_name: "Japanese Grammar in Action"},
{breadth_name: "Music Language 2: Chromaticism & Beyond"},
{breadth_name: "Intensive Syriac Aramaic"},
{breadth_name: "Sustainable Food Systems"},
{breadth_name: "Probability for Statistics"},
{breadth_name: "Thinking about Science: Past and Present"},
{breadth_name: "Science and Pseudoscience"},
{breadth_name: "Introduction to Mathematics"},
{breadth_name: "Economics of Financial Markets"},
{breadth_name: "Objectivity and Value"},
{breadth_name: "Cross-Cultural Management and Teamwork"},
{breadth_name: "Japanese 6"},
{breadth_name: "Drawing, Painting and Sensory Knowing"},
{breadth_name: "Contemporary Art and Biomedicine"},
{breadth_name: "German 5"},
{breadth_name: "Chinese Economic Documents"},
{breadth_name: "Music, Learning and Popular Musicians"},
{breadth_name: "Formative Ideas in Architecture"},
{breadth_name: "Hashtag Cyberstar"},
{breadth_name: "American Classics"},
{breadth_name: "Flora of Victoria"},
{breadth_name: "Practical Chemistry 2"},
{breadth_name: "International Gender Politics"},
{breadth_name: "Critical and Theoretical Studies 3"},
{breadth_name: "Shakuhachi Ensemble 1"},
{breadth_name: "Key Challenges for Asia"},
{breadth_name: "Reproductive Physiology"},
{breadth_name: "Food Processing & Preservation"},
{breadth_name: "Latin 2"},
{breadth_name: "Sexualising Society: Sociology of Sex"},
{breadth_name: "Biological Psychology"},
{breadth_name: "Russian 5"},
{breadth_name: "Digital Technology and Social Change"},
{breadth_name: "Composition Studies"},
{breadth_name: "Business Decision Analysis"},
{breadth_name: "Intensive French 3 and 4"},
{breadth_name: "Chinese Cinema"},
{breadth_name: "Sound Studies 2"},
{breadth_name: "Diversity: Identities in Indonesia"},
{breadth_name: "Avant-Garde and Postmodern Art"},
{breadth_name: "Wine & Spirits:An Australian Perspective"},
{breadth_name: "Industrial Economics"},
{breadth_name: "Measurement of Building Works"},
{breadth_name: "Arabic in Context 2"},
{breadth_name: "Free Speech and Media Law"},
{breadth_name: "Applied Animal Behaviour"},
{breadth_name: "Indonesian 3"},
{breadth_name: "Macroeconomics"},
{breadth_name: "Video Games: Remaking Reality"},
{breadth_name: "Beer Styles and Sensory Analysis"},
{breadth_name: "Inequalities: Causes and Consequences"},
{breadth_name: "German 4"},
{breadth_name: "Construction Design"},
{breadth_name: "Genes: Organisation and Function"},
{breadth_name: "Mobile Worlds"},
{breadth_name: "Positive Leadership and Careers"},
{breadth_name: "Arabic 4"},
{breadth_name: "Guitar Group 1"},
{breadth_name: "Engineering Computation"},
{breadth_name: "Hebrew 2"},
{breadth_name: "Calculus 1"},
{breadth_name: "In the Heart of the Loire Valley"},
{breadth_name: "Financial Accounting Theory"},
{breadth_name: "Science and Society"},
{breadth_name: "Concepts in Cell & Developmental Biology"},
{breadth_name: "Our Planet, Our Health"},
{breadth_name: "Sex, Gender and Power"},
{breadth_name: "Database Systems"},
{breadth_name: "Indonesian 2"},
{breadth_name: "Graphic Design Studio 2: Image & Media"},
{breadth_name: "Fluid Mechanics"},
{breadth_name: "Human Physiology"},
{breadth_name: "Ancient Greek 1"},
{breadth_name: "Media and Urban Culture in Asia"},
{breadth_name: "Asian Arts: Networks and Hubs"},
{breadth_name: "The Environmental Screenscape"},
{breadth_name: "School Experience as Breadth"},
{breadth_name: "Animal Physiology and Growth"},
{breadth_name: "Minds and Madness"},
{breadth_name: "Field Mapping and Sedimentary Geology"},
{breadth_name: "Italian 4"},
{breadth_name: "Italian 3"},
{breadth_name: "The Renaissance in Italy"},
{breadth_name: "Japanese 8"},
{breadth_name: "Environmental Economics"},
{breadth_name: "Analytical & Environmental Chemistry"},
{breadth_name: "Gender in Hispanic Cultures"},
{breadth_name: "Economic Geology"},
{breadth_name: "Interactive Art Media 1"},
{breadth_name: "Ethical Theory"},
{breadth_name: "Marine Ecosystems: Ecology & Management"},
{breadth_name: "Philosophy, Politics and Economics"},
{breadth_name: "Sociology of Youth"},
{breadth_name: "Drugs: From Discovery to Market"},
{breadth_name: "Magic, Reason, New Worlds, 1450-1750"},
{breadth_name: "Applied Ecology"},
{breadth_name: "Ancient Greek 6"},
{breadth_name: "Differential Equations"},
{breadth_name: "Corporate Power and White Collar Crime"},
{breadth_name: "Past Climates: Icehouse to Greenhouse"},
{breadth_name: "Studies In Opera"},
{breadth_name: "Chinese Politics and Society"},
{breadth_name: "Matters of Taste: French Eating Cultures"},
{breadth_name: "Taxation Law I"},
{breadth_name: "Beyond Babylon"},
{breadth_name: "Plant Evolution"},
{breadth_name: "Archaeology of the Roman World"},
{breadth_name: "Gender in History, 1800 to the Present"},
{breadth_name: "Economics of the Environment"},
{breadth_name: "Law and Cultural Industries"},
{breadth_name: "Corporate Law"},
{breadth_name: "Engineering Mechanics"},
{breadth_name: "Phenomenology and Existentialism"},
{breadth_name: "Managing the Multinational"},
{breadth_name: "Shakespeare in Performance"},
{breadth_name: "Sedimentary Geology"},
{breadth_name: "Up Close and Personal with MTC"},
{breadth_name: "God and the Natural Sciences"},
{breadth_name: "Construction of Concrete Buildings"},
{breadth_name: "Health Economics"},
{breadth_name: "Geobiology: Fossils & Environments"},
{breadth_name: "Experiencing Foodscapes: Italy & Spain"},
{breadth_name: "Venice and Cultures of Consumption"},
{breadth_name: "Sub-atomic Physics"},
{breadth_name: "Learning via Sport and Outdoor Education"},
{breadth_name: "Climate Change ll"},
{breadth_name: "German Cultural Studies A"},
{breadth_name: "An Ecological History of Humanity"},
{breadth_name: "Chinese 3"},
{breadth_name: "Steel and Concrete Structural Systems"},
{breadth_name: "Islam and Modernity"},
{breadth_name: "Behavioural Economics"},
{breadth_name: "Global Environmental Politics"},
{breadth_name: "Body, Mind and Medicine: A Dissection"},
{breadth_name: "Art History: Theory and Controversy"},
{breadth_name: "Foundations of Informatics"},
{breadth_name: "Jazz: The Improvisatory Spirit"},
{breadth_name: "European Art & Absolute Power 1660-1815"},
{breadth_name: "Managing Strategic Change"},
{breadth_name: "Second Language Learning and Teaching"},
{breadth_name: "Developmental Biology"},
{breadth_name: "Sex, Gender and Culture: An Introduction"},
{breadth_name: "Music and Health"},
{breadth_name: "Introductory Macroeconomics"},
{breadth_name: "Algebra"},
{breadth_name: "Global Pop"},
{breadth_name: "European Modernism"},
{breadth_name: "Quantitative Methods 2"},
{breadth_name: "Perception, Memory and Cognition"},
{breadth_name: "Music in the Culture of the Renaissance"},
{breadth_name: "Short Fiction"},
{breadth_name: "Mathematical Economics"},
{breadth_name: "Principles of Microbiology & Immunology"},
{breadth_name: "Space in Performance"},
{breadth_name: "French Travel Writing"},
{breadth_name: "USA and the World"},
{breadth_name: "Genetics, Health, and Society"},
{breadth_name: "Landscape Ecosystem Project"},
{breadth_name: "Information Security and Privacy"},
{breadth_name: "Science, Technology and Public Policy"},
{breadth_name: "Terrorism: Shifting Paradigms"},
{breadth_name: "Inequalities: Challenges for the Future"},
{breadth_name: "Physics 2: Physical Science & Technology"},
{breadth_name: "Water for Sustainable Futures"},
{breadth_name: "A Taste of Europe: Melbourne Intensive"},
{breadth_name: "Ensemble Filmmaking, Art and Industry"},
{breadth_name: "The Business of Music"},
{breadth_name: "Critical and Theoretical Studies 1"},
{breadth_name: "Australian Politics"},
{breadth_name: "Wellbeing, Motivation and Performance"},
{breadth_name: "Physics 1: Advanced"},
{breadth_name: "Irrigation and Water Management"},
{breadth_name: "Trends in Personality& Social Psychology"},
{breadth_name: "Chemical Process Analysis"},
{breadth_name: "Design and Property Industry Studies"},
{breadth_name: "Environmental Risk Assessment"},
{breadth_name: "Science Research Project"},
{breadth_name: "Modelling the Real World"},
{breadth_name: "Story, Children and the Arts"},
{breadth_name: "Indigenous Treaties and Titles"},
{breadth_name: "Forests in a Global Context"},
{breadth_name: "Spontaneous Drama:Improv and Communities"},
{breadth_name: "Real and Artificial Neural Networks"},
{breadth_name: "String Ensemble 1"},
{breadth_name: "Literacy, Power and Learning"},
{breadth_name: "Business in Asia"},
{breadth_name: "Sport and the Law"},
{breadth_name: "Environmental Building Systems"},
{breadth_name: "Animal Structure and Function"},
{breadth_name: "Global Criminology"},
{breadth_name: "Latin 1"},
{breadth_name: "Biology: Life's Machinery"},
{breadth_name: "Ancient Egyptian 4"},
{breadth_name: "Choir 1"},
{breadth_name: "Hollywood and Entertainment"},
{breadth_name: "Tectonics & Geodynamics"},
{breadth_name: "Variation in Japanese Language"},
{breadth_name: "Popular Fiction"},
{breadth_name: "Intro to Food Science & Human Nutrition"},
{breadth_name: "Russian 1"},
{breadth_name: "Spanish 5"},
{breadth_name: "Indonesian Languages in Social Context"},
{breadth_name: "Neurophysiology: Neurons and Circuits"},
{breadth_name: "Language in Aboriginal Australia"},
{breadth_name: "Sustainability in Developing Communities"},
{breadth_name: "Urban Design for People and Places"},
{breadth_name: "Music Psychology"},
{breadth_name: "Indigenous Education in Community"},
{breadth_name: "Introduction to Indigenous Education"},
{breadth_name: "Keeping the Body in Mind"},
{breadth_name: "Reactor Engineering"},
{breadth_name: "Positive Communities and Organisations"},
{breadth_name: "First Peoples in a Global Context"},
{breadth_name: "Introductory Biology: Life's Complexity"},
{breadth_name: "Thinking Tools for Wicked Problems"},
{breadth_name: "Design and Property Studio"},
{breadth_name: "Contemporary Chinese Literature"},
{breadth_name: "Gothic Fictions"},
{breadth_name: "Ecology"},
{breadth_name: "The Unconscious Mind"},
{breadth_name: "Youth Culture and the Arts"},
{breadth_name: "Screening Europe: Image and Identity"},
{breadth_name: "Feminism"},
{breadth_name: "Modern Israel: Good Bad and Disputed"},
{breadth_name: "Global Cultures"},
{breadth_name: "Entrepreneurship Principles and Tools"},
{breadth_name: "Discrete Maths and Operations Research"},
{breadth_name: "Underworld and Afterlife"},
{breadth_name: "AUSLAN and Visual Communication"},
{breadth_name: "Spatial Analysis in Geography"},
{breadth_name: "Young People, Crime and Justice"},
{breadth_name: "Chinese 5"},
{breadth_name: "Anthropology of Kinship and Family"},
{breadth_name: "From Plato to Einstein"},
{breadth_name: "Islam and Muslim Societies: Introduction"},
{breadth_name: "Creative Projects-Digital Technologies"},
{breadth_name: "Red Empire: The Soviet Union and After"},
{breadth_name: "Sociology of Work: The Future of Work"},
{breadth_name: "Television, Lifestyle & Consumer Culture"},
{breadth_name: "University Symphonic Ensembles 2"},
{breadth_name: "Chemistry 1"},
{breadth_name: "Imperial Rome: Mediterranean Superpower"},
{breadth_name: "The Art of Game Music"},
{breadth_name: "Introduction to Urban Planning"},
{breadth_name: "City Visions: Melbourne Intensive"},
{breadth_name: "Discourse & Pragmatics"},
{breadth_name: "Earth Composition, Minerals and Magmas"},
{breadth_name: "The Secret Life of the Body 1"},
{breadth_name: "French 6"},
{breadth_name: "Neuromarketing"},
{breadth_name: "Fire in the Australian Landscape"},
{breadth_name: "Politics and the Media"},
{breadth_name: "Stochastic Modelling"},
{breadth_name: "Fundamentals of Chemistry"},
{breadth_name: "Space Studio"},
{breadth_name: "Contemporary Aboriginal Art"},
{breadth_name: "Ancient Greek 4"},
{breadth_name: "Design Studio Beta"},
{breadth_name: "Discrete Mathematics"},
{breadth_name: "Science, Reason and Reality"},
{breadth_name: "Development of the Thinking Child"},
{breadth_name: "Light in Performance"},
{breadth_name: "Linear Algebra: Advanced"},
{breadth_name: "Literature, Adaptation, Media"},
{breadth_name: "Principles of Brewing"},
{breadth_name: "Indonesia in the World"},
{breadth_name: "Introduction to Screen Studies"},
{breadth_name: "Accounting Reports and Analysis"},
{breadth_name: "Dancing the Dance 2: Create & Perform"},
{breadth_name: "Design and Property Principles"},
{breadth_name: "Semantics"},
{breadth_name: "Sexing the Canvas: Art and Gender"},
{breadth_name: "Biosystems Design"},
{breadth_name: "Italian Cultural Studies A"},
{breadth_name: "Chinese Music Ensemble 1"},
{breadth_name: "Hebrew 5"},
{breadth_name: "Justice, Freedom and Equality"},
{breadth_name: "Introduction to Screenwriting Practices"},
{breadth_name: "Chinese in Context 1"},
{breadth_name: "The Australian Imaginary"},
{breadth_name: "Wines of the World"},
{breadth_name: "Israelis & Palestinians: Conflict, Peace"},
{breadth_name: "Introduction to Actuarial Studies"},
{breadth_name: "Hispanic Cultural Studies"},
{breadth_name: "Principles of Chemical Biology"},
{breadth_name: "Life Writing"},
{breadth_name: "Seeing: The Whole Picture"},
{breadth_name: "Strategic Marketing"},
{breadth_name: "Japanese 7"},
{breadth_name: "Chinese Business and Economy"},
{breadth_name: "The Secret Life of Language"},
{breadth_name: "Energy and the Environment"},
{breadth_name: "Organisations, Economics and Incentives"},
{breadth_name: "Staging Theatre for Youth Audiences"},
{breadth_name: "Myth, Art and Empire: Greece and Rome"},
{breadth_name: "Field Archaeology"},
{breadth_name: "Expertise and Your Professional Career"},
{breadth_name: "Plant Molecular Biology & Biotechnology"},
{breadth_name: "Social Problems in Japan"},
{breadth_name: "The Rise of the Novel"},
{breadth_name: "Hebrew 3"},
{breadth_name: "Creativity, Genius, Expertise and Talent"},
{breadth_name: "Valuation of Land and Buildings"},
{breadth_name: "Sports Economics"},
{breadth_name: "Earth Processes for Engineering"},
{breadth_name: "Advertising and Promotions"},
{breadth_name: "Signals and Systems"},
{breadth_name: "Geographies of Migration"},
{breadth_name: "Advanced Topics in Nutrition"},
{breadth_name: "Australia in the Wine World"},
{breadth_name: "Aboriginal Writing"},
{breadth_name: "History of Economic Thought"},
{breadth_name: "Ancient Egypt and Mesopotamia"},
{breadth_name: "Introduction to Biomechanics"},
{breadth_name: "Health Geography"},
{breadth_name: "Art and Revolution"},
{breadth_name: "Korean 4"},
{breadth_name: "Livestock Production Systems"},
{breadth_name: "Infographics Studio"},
{breadth_name: "Intellectual Property Law"},
{breadth_name: "The First Centuries of Islam"},
{breadth_name: "Philosophy of Language"},
{breadth_name: "The Social History of the Roman World"},
{breadth_name: "Sport, Leadership and the Community"},
{breadth_name: "Managing Entrepreneurship and Innovation"},
{breadth_name: "Modern Architecture: MoMo to PoMo"},
{breadth_name: "French Cinema: The New Wave and Beyond"},
{breadth_name: "Actuarial Statistics"},
{breadth_name: "Econometrics 1"},
{breadth_name: "The Electronic Arts: Vision and Sound"},
{breadth_name: "Music History 3:Impressionism to Present"},
{breadth_name: "Modern and Future Climate"},
{breadth_name: "Laboratory Work B"},
{breadth_name: "A History of Nature"},
{breadth_name: "Evolution: Making Sense Of Life"},
{breadth_name: "Rock, Pop & Resistance"},
{breadth_name: "Japanese 4"},
{breadth_name: "Shaping the Enterprise with ICT"},
{breadth_name: "Wagner's Ring"},
{breadth_name: "Principles of Human Structure"},
{breadth_name: "Living in a Risk Society"},
{breadth_name: "Drugs That Shape Society"},
{breadth_name: "Modern and Contemporary Chinese Art"},
{breadth_name: "Analysing Professional Communication"},
{breadth_name: "Construction Analysis"},
{breadth_name: "Enterprise Performance Management"},
{breadth_name: "Biotechnology in Practice"},
{breadth_name: "Ancient Egyptian 2"},
{breadth_name: "Korean Politics and Society"},
{breadth_name: "Entrepreneurship and Product Innovation"},
{breadth_name: "Group Theory and Linear Algebra"},
{breadth_name: "The Rise and Fall of the Roman Republic"},
{breadth_name: "Italian 7"},
{breadth_name: "Complex Functions in Neuroscience"},
{breadth_name: "Advanced Field Geology"},
{breadth_name: "Electrical Device Modelling"},
{breadth_name: "Food & Water:Global Issues Local Impacts"},
{breadth_name: "Music and Politics"},
{breadth_name: "Indonesian Politics and Society"},
{breadth_name: "Labour Economics"},
{breadth_name: "Consultants and Government"},
{breadth_name: "Indonesian 6"},
{breadth_name: "Arabic in Context 1"},
{breadth_name: "Hebrew 1"},
{breadth_name: "Arabic 7"},
{breadth_name: "Foundations of Genetics and Genomics"},
{breadth_name: "Romanticism to Decadence: French Novels"},
{breadth_name: "Methods in Agrifood Biotechnology"},
{breadth_name: "Literature, Environment, Crisis"},
{breadth_name: "Latin 6"},
{breadth_name: "Italian 2"},
{breadth_name: "Taiwan & Beyond: Chinese Settler Culture"},
{breadth_name: "Material and Energy Balances"},
{breadth_name: "Queer Lives"},
{breadth_name: "Indigenous Cultural Heritage"},
{breadth_name: "Latin 5"},
{breadth_name: "Resource Management Economics"},
{breadth_name: "Pop Song Writing 1"},
{breadth_name: "Managing Justice: Agencies and the State"},
{breadth_name: "Applying Coaching Science"},
{breadth_name: "Comparative Politics"},
{breadth_name: "Managing People at Work"},
{breadth_name: "Self, Culture and Society"},
{breadth_name: "Basic Econometrics"},
{breadth_name: "Applications of GIS"},
{breadth_name: "History of Greece: Homer to Alexander"},
{breadth_name: "Computer Systems"},
{breadth_name: "Italian Cultural Studies B"},
{breadth_name: "Introduction to Islamic Spirituality"},
{breadth_name: "Global Youth"},
{breadth_name: "German 2"},
{breadth_name: "Game Design"},
{breadth_name: "Digital Marketing"},
{breadth_name: "Graphic Design Studio 1: Image & Text"},
{breadth_name: "Guitar Group 2"},
{breadth_name: "Thermodynamics and Fluid Mechanics"},
{breadth_name: "Intensive Ancient Greek 1"},
{breadth_name: "Work and Conflict in the Global Economy"},
{breadth_name: "Sex and Gender in the Sciences"},
{breadth_name: "American History: Revolution to WWII"},
{breadth_name: "Comparative Legal Traditions"},
{breadth_name: "Genders, Bodies & Sexualities"},
{breadth_name: "Introductory Financial Mathematics"},
{breadth_name: "Weather and Climate Systems"},
{breadth_name: "Environmental Geosciences"},
{breadth_name: "Law in Society"},
{breadth_name: "Digital System Design"},
{breadth_name: "Plant Biodiversity"},
{breadth_name: "Evolutionary Genetics and Genomics"},
{breadth_name: "Experimental Economics"},
{breadth_name: "Law, Justice and Social Change"},
{breadth_name: "Japanese 1"},
{breadth_name: "The Global Environment"},
{breadth_name: "Cities: From Local to Global"},
{breadth_name: "Still Life: Nature Morte"},
{breadth_name: "Mechanics & Materials"},
{breadth_name: "Creative Writing: Ideas and Practice"},
{breadth_name: "Vine to Wine"},
{breadth_name: "Australia Now"},
{breadth_name: "Academic English 2"},
{breadth_name: "Asian Century: Meaning and Impact"},
{breadth_name: "Post-Conflict Development and Difference"},
{breadth_name: "Heat and Mass Transport Processes"},
{breadth_name: "Applied Microeconometric Modelling"},
{breadth_name: "Trends & Issues in Agrifood Biotech"},
{breadth_name: "Managing Work and Your Career"},
{breadth_name: "Electronic System Implementation"},
{breadth_name: "Renaissance Art in Global Context"},
{breadth_name: "Contemporary Japan"},
{breadth_name: "Lived Religion in an Uncertain World"},
{breadth_name: "Principles of Finance"},
{breadth_name: "Engineering Materials"},
{breadth_name: "Rebels and Revolutionaries"},
{breadth_name: "Creativity, Play and the Arts"},
{breadth_name: "Arabic 1"},
{breadth_name: "Accelerated Mathematics 1"},
{breadth_name: "The Medieval Image: Art and Culture"},
{breadth_name: "Digital Design"},
{breadth_name: "Algorithmic Trading"},
{breadth_name: "Roman Law in Context"},
{breadth_name: "Principles of Building"},
{breadth_name: "Choir 2"},
{breadth_name: "Egypt Under the Pharaohs"},
{breadth_name: "Medical Microbiology: Bacteriology"},
{breadth_name: "World Music Choir"},
{breadth_name: "Foundations of Computing"},
{breadth_name: "Chinese 8"},
{breadth_name: "Sociology of Culture"},
{breadth_name: "Global Inequalities In The Anthropocene"},
{breadth_name: "Creative Industries in Indonesia"},
{breadth_name: "Public Policy Making"},
{breadth_name: "Logical Methods"},
{breadth_name: "Business Economics and e-Commerce"},
{breadth_name: "Principles of Business Law"},
{breadth_name: "Philosophy: The Big Questions"},
{breadth_name: "Principles of Marketing"},
{breadth_name: "Web Information Technologies"},
{breadth_name: "Rock Music: From Roots to Retro"},
{breadth_name: "Art Cinema and the Love Story"},
{breadth_name: "Eurovisions"},
{breadth_name: "Managing Employee Relations"},
{breadth_name: "International Relations: Key Questions"},
{breadth_name: "Two Koreas in the World"},
{breadth_name: "Literature and Performance"},
{breadth_name: "Drugs in Biomedical Experiments"},
{breadth_name: "Modern and Contemporary Literature"},
{breadth_name: "Chemistry: Structure and Properties"},
{breadth_name: "Evolution and the Human Condition"},
{breadth_name: "The Music Producer: From Brass to Beats"},
{breadth_name: "Design Studio Alpha"},
{breadth_name: "Money and Banking"},
{breadth_name: "International Corporate Governance"},
{breadth_name: "Actuarial Modelling II"},
{breadth_name: "Music, Mind & Wellbeing"},
{breadth_name: "Youth and Popular Culture"},
{breadth_name: "Contemporary Korea"},
{breadth_name: "Contested Resources"},
{breadth_name: "Business Forensics and Fraud"},
{breadth_name: "Australian Economic History"},
{breadth_name: "Spanish 4"},
{breadth_name: "Environmental Rights & Responsibilities"},
{breadth_name: "Australian Politics in the Long Run"},
{breadth_name: "Consumer Law"},
{breadth_name: "Principles of Immunology"},
{breadth_name: "Latin 3"},
{breadth_name: "City Cultures, Urban Ecologies"},
{breadth_name: "Analysis of Contemporary Chinese Society"},
{breadth_name: "Greek Philosophy"},
{breadth_name: "The Politics of Sex"},
{breadth_name: "Fertility, Mortality and Social Change"},
{breadth_name: "Chinese 6"},
{breadth_name: "Nietzsche and Critics"},
{breadth_name: "New Caledonia in the 21st Century"},
{breadth_name: "Fundamentals of Cell Biology"},
{breadth_name: "American History: 1945 to Now"},
{breadth_name: "Genetic Analysis"},
{breadth_name: "Computational Economics and Business"},
{breadth_name: "From the Solar System to the Cosmos"},
{breadth_name: "Understanding Society"},
{breadth_name: "Animals and Society 2: Humans & Animals"},
{breadth_name: "Laboratory Work A"},
{breadth_name: "Anthropology: Studying Self and Other"},
{breadth_name: "Knowledge and Reality"},
{breadth_name: "Economic Tools for the Environment"},
{breadth_name: "Physics 2: Life Sciences & Environment"},
{breadth_name: "Decadent Literature"},
{breadth_name: "Biology: Life's Complexity"},
{breadth_name: "Drawing with Anatomy"},
{breadth_name: "German Cultural Studies B"},
{breadth_name: "Modern and Contemporary Theatre"},
{breadth_name: "The Romantic Piano"},
{breadth_name: "Language, Society and Culture"},
{breadth_name: "Philosophy: The Great Thinkers"},
{breadth_name: "Planning Scenario and Policy Workshop"},
{breadth_name: "Understanding Planet Earth"},
{breadth_name: "Chinese 10"},
{breadth_name: "Foundations of Information Systems"},
{breadth_name: "Indonesian Gamelan Ensemble"},
{breadth_name: "Economic Development"},
{breadth_name: "Global Marketing"},
{breadth_name: "Popular Culture: From K-pop to Selfies"},
{breadth_name: "Chinese Studies: Culture and Empire"},
{breadth_name: "Crime, Criminology, and Critique"},
{breadth_name: "Japanese Through the Media"},
{breadth_name: "Debating Science in Society"},
{breadth_name: "Dancing the Dance 1"},
{breadth_name: "Ancient Greek 3"},
{breadth_name: "Writing Identity and Difference"},
{breadth_name: "Pirates and their Enemies"},
{breadth_name: "Tales of Muslim Spain"},
{breadth_name: "Drugs Affecting the Nervous System"},
{breadth_name: "Ancient & Contemporary Indigenous Arts"},
{breadth_name: "Physics 2: Advanced"},
{breadth_name: "Russian 6"},
{breadth_name: "Paris! Berlioz to the Ballets Russes"},
{breadth_name: "Australia in the World"},
{breadth_name: "Competition and Strategy"},
{breadth_name: "Freedom and Equality Across Borders"},
{breadth_name: "Design Studio Epsilon"},
{breadth_name: "Time Series Analysis and Forecasting"},
{breadth_name: "Blue Planet-Intro to Marine Environments"},
{breadth_name: "Marketing and Society"},
{breadth_name: "International Trade Policy"},
{breadth_name: "The Philosophy of Mind"},
{breadth_name: "Electricity and Enlightenment History"},
{breadth_name: "Writing for Screen"},
{breadth_name: "Geology of Southeast Australia"},
{breadth_name: "Chemistry for BioSciences"},
{breadth_name: "Indonesian 4"},
{breadth_name: "Classic Chinese Civilisation"},
{breadth_name: "Critical Thinking With Data"},
{breadth_name: "Gender Diversity in the Workplace"},
{breadth_name: "Introduction to Political Ideas"},
{breadth_name: "Introductory Personal Finance"},
{breadth_name: "Foundations of Physics"},
{breadth_name: "Morphology"},
{breadth_name: "Dangerous Earth"},
{breadth_name: "Language and Identity"},
{breadth_name: "Contingencies"},
{breadth_name: "Imaging the Environment"},
{breadth_name: "Comparative Nutrition and Digestion"},
{breadth_name: "The Nature of Reality"},
{breadth_name: "Stalinism"},
{breadth_name: "Making Movies 3 Practical Production"},
{breadth_name: "Cities Past and Future"},
{breadth_name: "Introductory Financial Accounting"},
{breadth_name: "The Qur'an: An Introduction"},
{breadth_name: "Engineering Mathematics"},
{breadth_name: "Hispanic Film Today"},
{breadth_name: "Biochemistry and Molecular Biology"},
{breadth_name: "Sex and Gender Present and Future"},
{breadth_name: "Plant Breeding and Genetics"},
{breadth_name: "Imaging Italy"},
{breadth_name: "Environmental Chemistry"},
{breadth_name: "Managing Globally"},
{breadth_name: "To Hell with Dante"},
{breadth_name: "Australian Wildlife Biology"},
{breadth_name: "Indigenous Cultures and Knowledges"},
{breadth_name: "Colour Studio"},
{breadth_name: "Project Management"},
{breadth_name: "Biotechnology"},
{breadth_name: "China in Transition"},
{breadth_name: "Neuroscience and the Mind"},
{breadth_name: "Systems Modelling and Design"},
{breadth_name: "Signs and Symbols in Japanese"},
{breadth_name: "International Politics"},
{breadth_name: "Regulating Digital Platforms"},
{breadth_name: "Australian Film and Television"},
{breadth_name: "Urban Forest Ecosystems"},
{breadth_name: "Media, Identity and Everyday Life"},
{breadth_name: "Developmental Neurobiology"},
{breadth_name: "The Age of Alexander the Great"},
{breadth_name: "Sex, Death and the Ecstatic in Music"},
{breadth_name: "Policing"},
{breadth_name: "Practical Archaeology"},
{breadth_name: "Australian Art"},
{breadth_name: "Earth's Microbiomes"},
{breadth_name: "Local Sites, Global Connections"},
{breadth_name: "Science Communication and Employability"},
{breadth_name: "Music as Noise: Making Sound Art"},
{breadth_name: "Ethics, gender and the family"},
{breadth_name: "Italian 9"},
{breadth_name: "Sustainability: hope for the Earth?"},
{breadth_name: "Art and the Botanical"},
{breadth_name: "Green Infrastructure Technologies"},
{breadth_name: "Topics in Ethnomusicology"},
{breadth_name: "Ancient Greek 2"},
{breadth_name: "Cold War Cultures in Asia"},
{breadth_name: "Chinese Music Ensemble 2"},
{breadth_name: "Theoretical Physics 2"},
{breadth_name: "Music History 1: Monteverdi to Mozart"},
{breadth_name: "Political Economy"},
{breadth_name: "Electrodynamics"},
{breadth_name: "Italian 5A"},
{breadth_name: "Poetry, Love, and Death"},
{breadth_name: "Cooking up the Nation"},
{breadth_name: "Introduction to Language Translation"},
{breadth_name: "Intercultural Communication"},
{breadth_name: "First Language Acquisition"},
{breadth_name: "Econometrics 2"},
{breadth_name: "Art in Medieval Europe"},
{breadth_name: "Sociology of 'Race' and Ethnicities"},
{breadth_name: "Topics in Animal Health"},
{breadth_name: "Economics of the Law"},
{breadth_name: "Democracy and its Dilemmas"},
{breadth_name: "Research Methods for Planners"},
{breadth_name: "Singing, Song Writing and Youth Music"},
{breadth_name: "Introduction to Life, Earth and Universe"},
{breadth_name: "Global Health, Security & Sustainability"},
{breadth_name: "Circuits and Systems"},
{breadth_name: "Retailing"},
{breadth_name: "Sports Coaching: Theory and Practice"},
{breadth_name: "Finance for Built Environment"},
{breadth_name: "The Future of Work"},
{breadth_name: "Principles of Neuroscience"},
{breadth_name: "The Art of Working Online"},
{breadth_name: "Australian Indigenous Public Policy"},
{breadth_name: "Arts in Florence"},
{breadth_name: "Crime and Culture"},
{breadth_name: "Technology & Contemporary Life"},
{breadth_name: "Construction Management"},
{breadth_name: "Italian 1"},
{breadth_name: "Comedy"},
{breadth_name: "Understanding the Built Environment"},
{breadth_name: "Puppets as Storytellers"},
{breadth_name: "Introduction to Printmaking Processes"},
{breadth_name: "Agribusiness Marketing & Value Chains"},
{breadth_name: "Spanish 7"},
{breadth_name: "Contemporary Political Theory"},
{breadth_name: "The Theatre Experience"},
{breadth_name: "Economic Analysis and Policy"},
{breadth_name: "Singing and the Power of Pop Music"},
{breadth_name: "Creative Non Fiction"},
{breadth_name: "Art and Indigenous Voice"},
{breadth_name: "Human Rights and Global Justice"},
{breadth_name: "Realities and Fictions of Argentina"},
{breadth_name: "A History of Violence"},
{breadth_name: "Japanese through the Media"},
{breadth_name: "Corporate Financial Decision Making"},
{breadth_name: "Samba Band"},
{breadth_name: "Going Places - Travelling Smarter"},
{breadth_name: "Improvisation: Text, Space and Action"},
{breadth_name: "Risk Management and Citizen Science"},
{breadth_name: "Interpreting Australian Landscape Design"},
{breadth_name: "The Actors Process"},
{breadth_name: "Islam and Democracy"},
{breadth_name: "Australian Indigenous Politics"},
{breadth_name: "Arts Internship: Not for Profit"},
{breadth_name: "Topics in Musicology"},
{breadth_name: "Comparing Media Systems"},
{breadth_name: "Managing in Contemporary Organisations"},
{breadth_name: "Crisis, Culture and Resistance"},
{breadth_name: "Branding"},
{breadth_name: "Design Studio Gamma"},
{breadth_name: "Phonology"},
{breadth_name: "African Music and Dance Ensemble"},
{breadth_name: "Russian 4"},
{breadth_name: "Film Noir: History and Sexuality"},
{breadth_name: "Hitler's Germany and Fascism"},
{breadth_name: "Economics of Food Markets"},
{breadth_name: "Learning and the Digital Generations"},
{breadth_name: "Disability, Diversity and Inclusion"},
{breadth_name: "Innovation Change & Knowledge Transfer"},
{breadth_name: "Italian 1 (Intensive)"},
{breadth_name: "Global Foundations of Design"},
{breadth_name: "Modern China in Global History 1949-1999"},
{breadth_name: "Ancient Egyptian 1"},
{breadth_name: "Health Law, Ethics and Society"},
{breadth_name: "Britain's Empire: Power and Resistance"},
{breadth_name: "Arabic 9"},
{breadth_name: "Language and Power in Asian Societies"},
{breadth_name: "Performance and the World"},
{breadth_name: "Peak Performance Under Pressure"},
{breadth_name: "Optimising Personal Performance"},
{breadth_name: "Community Volunteering - Global"},
{breadth_name: "The Great War 1914 to 1918"},
{breadth_name: "Understanding Australian Media"},
{breadth_name: "Business Analytics"},
{breadth_name: "Foundations of FinTech"},
{breadth_name: "The Music Of Spain"},
{breadth_name: "Sound in Performance"},
{breadth_name: "French 1"},
{breadth_name: "Legal Language"},
{breadth_name: "Russian Culture Through Film"},
{breadth_name: "Performance, Potential and Development"},
{breadth_name: "Baroque Ensemble 1"},
{breadth_name: "Musics of the World"},
{breadth_name: "Melbourne Big Band 1"},
{breadth_name: "Investments"},
{breadth_name: "Intensive Akkadian 2"},
{breadth_name: "Environmental Design in Housing"},
{breadth_name: "Inside the City of Diversity"},
{breadth_name: "Environmental Design- Commercial"},
{breadth_name: "Education and Social Movements"},
{breadth_name: "Critical Analytical Skills"},
{breadth_name: "Transgender Studies Terms and Debates"},
{breadth_name: "Ethics in Finance"},
{breadth_name: "The Dynamics of Scientific Change"},
{breadth_name: "Arabic 10"},
{breadth_name: "Marketing Communications"},
{breadth_name: "Indigenous Australia"},
{breadth_name: "Politics in the Middle East & South Asia"},
{breadth_name: "Thinking Sex"},
{breadth_name: "Concepts of Childhood"},
{breadth_name: "Market and Business Research"},
{breadth_name: "Derivative Securities"},
{breadth_name: "Law, Science and Power"},
{breadth_name: "Archaeology of the Classical Greek World"},
{breadth_name: "Law in Social Theory"},
{breadth_name: "Diplomat, Soldier, Spy: The Deep State"},
{breadth_name: "Clear Speech and Communication"},
{breadth_name: "Introduction to Indigenous History"},
{breadth_name: "Russian 2"},
{breadth_name: "Topics in Popular Music Studies"},
{breadth_name: "Indigenous Astronomy"},
{breadth_name: "Approaches to Media Research"},
{breadth_name: "Decolonising the Landscape MultiStudio 1"},
{breadth_name: "Global Intersections:Gender, Race, Class"},
{breadth_name: "Natural History"},
{breadth_name: "Art, Market and Methods"},
{breadth_name: "Introduction to Japanese Communication"},
{breadth_name: "Knowledge, Learning and Culture"},
{breadth_name: "Global Theatre History"},
{breadth_name: "French and Francophone Cultural Studies"},
{breadth_name: "Media and Society"},
{breadth_name: "Accounting Information: Risks & Controls"},
{breadth_name: "Australian Foreign Policy"},
{breadth_name: "Cybercrime and Digital Criminology"},
{breadth_name: "Power, Ideology and Inequality"},
{breadth_name: "Corruption, Transparency and Politics"},
{breadth_name: "Free Play New Music Improvisation Ensem"},
{breadth_name: "Construction Contract Administration"},
{breadth_name: "Chinese 4"},
{breadth_name: "The Secret Life of Students"},
{breadth_name: "Development in the 21st Century"},
{breadth_name: "Acting for Camera"},
{breadth_name: "Witch-Hunting in European Societies"},
{breadth_name: "Indonesian 1"},
{breadth_name: "Phonetics"},
{breadth_name: "Globalisation and the World Economy"},
{breadth_name: "On Country, On Campus: Wurundjeri"},
{breadth_name: "Sport, Education and the Media"},
{breadth_name: "Transit Oriented Development"},
{breadth_name: "Bad Science"},
{breadth_name: "Modern European History 1789 to 1914"},
{breadth_name: "Total War: World War II"},
{breadth_name: "The History of Cool: Fashion & Attitude"},
{breadth_name: "The Holocaust & Genocide"},
{breadth_name: "Interpreting Material Culture"},
{breadth_name: "Chinese 1"},
{breadth_name: "Anthropology of More-Than-Human Worlds"},
{breadth_name: "Insects Shaping Society"},
{breadth_name: "Global Literature and Postcolonialism"},
{breadth_name: "Food for a Healthy Planet III"},
{breadth_name: "Global Human Rights Law"},
{breadth_name: "Global Cultures of Japan and Korea"},
{breadth_name: "Intermediate Financial Accounting"},
{breadth_name: "Generating the Wealth of Nations"},
{breadth_name: "Music in Australia"},
{breadth_name: "Anthropology of Urban Life and Conflict"},
{breadth_name: "Melbourne Big Band 2"},
{breadth_name: "Eugenics: A Biopolitical History"},
{breadth_name: "The World Since World War II"},
{breadth_name: "Korean 1"},
{breadth_name: "Geochemistry & Petrogenesis"},
{breadth_name: "Modern Southeast Asia"},
{breadth_name: "Law Space: Geographies of Justice"},
{breadth_name: "Gender and Contemporary Culture"},
{breadth_name: "Real Analysis: Advanced"},
{breadth_name: "Ecology in Changing Environments"},
{breadth_name: "Elements of Data Processing"},
{breadth_name: "Perception, Illusions and Art"},
{breadth_name: "The Figure in Performance"},
{breadth_name: "Comparative Animal Physiology"},
{breadth_name: "Probability for Inference"},
{breadth_name: "Race in the Americas"},
{breadth_name: "Construction of Residential Buildings"},
{breadth_name: "Understanding Knowing and Learning"},
{breadth_name: "Quantum Physics"},
{breadth_name: "American Politics"},
{breadth_name: "Food Law and Policy"},
{breadth_name: "Syntax"},
{breadth_name: "Making Micro Movies - Filming the Real"},
{breadth_name: "Youth Leading Change"},
{breadth_name: "IT Project"},
{breadth_name: "Cognitive Psychology"},
{breadth_name: "Sustainable Development"},
{breadth_name: "Street Art"},
{breadth_name: "Green Planet: Plants and the Environment"},
{breadth_name: "Catastrophes as Turning Points"},
{breadth_name: "Metric and Hilbert Spaces"},
{breadth_name: "Decolonising the Landscape MultiStudio 2"},
{breadth_name: "Agronomy"},
{breadth_name: "Linear Statistical Models"},
{breadth_name: "Auditory Neuroscience"},
{breadth_name: "Landscapes and Environmental Change"},
{breadth_name: "Media Futures and New Technologies"},
{breadth_name: "Public Policy: Advocating for Change"},
{breadth_name: "Research Methods for Human Inquiry"},
{breadth_name: "Specialised Topics in Chemistry A"},
{breadth_name: "Frontiers in Veterinary Science"},
{breadth_name: "Tropical Field Ecology"},
{breadth_name: "Intro to Sustainable Water Management"},
{breadth_name: "Spatial Modelling for Nature and People"},
{breadth_name: "Dynamical Meteorology and Oceanography"},
{breadth_name: "Statistical Physics"},
{breadth_name: "Design of Algorithms"},
{breadth_name: "Applications of Genetics and Genomics"},
{breadth_name: "The Disaster Resilient City"},
{breadth_name: "Languages of Venice: Study Abroad"},
{breadth_name: "Media Computation"},
{breadth_name: "Mind, Brain & Behaviour 1"},
{breadth_name: "Hydrogeology/Environmental Geochemistry"},
{breadth_name: "The French Revolution"},
{breadth_name: "Taxation Law II"},
{breadth_name: "Human Behaviour and Environment"},
{breadth_name: "Animal Behaviour"},
{breadth_name: "Psychological Science: Theory & Practice"},
{breadth_name: "Specialised Topics in Chemistry B"},
{breadth_name: "Activism and Social Change in China"},
{breadth_name: "Food For a Healthy Planet II"},
{breadth_name: "Electronic Dance Music Technique"},
{breadth_name: "Complex Analysis"},
{breadth_name: "Deafness and Communication"},
{breadth_name: "Academic English 1"},
{breadth_name: "Riffs: Guitar Cultures & Practice 2"},
{breadth_name: "Music History 2: C19th Music and Ideas"},
{breadth_name: "Intensive Akkadian 1"},
{breadth_name: "French 2"},
{breadth_name: "Foundations of Digital Government"},
{breadth_name: "Creating Music For Advertising"},
{breadth_name: "The Developing World"},
{breadth_name: "The Modern Middle East"},
{breadth_name: "Gender, Rights, & Leadership in History"},
{breadth_name: "Surveying and Mapping"},
{breadth_name: "Media Histories"},
{breadth_name: "Area Studies in Ethnomusicology"},
{breadth_name: "Human Locomotor Systems"},
{breadth_name: "Thinking Scientifically"},
{breadth_name: "Advanced Screenwriting"},
{breadth_name: "The Psychopathology of Everyday Life"},
{breadth_name: "Drug Treatment of Disease"},
{breadth_name: "Fundamentals of Interaction Design"},
{breadth_name: "Elements of Quantum Computing"},
{breadth_name: "Developmental Psychology"},
{breadth_name: "Numerical Methods & Scientific Computing"},
{breadth_name: "Foundations of Design: Representation"},
{breadth_name: "Society and Environments"},
{breadth_name: "Mapping Environments"},
{breadth_name: "Astrophysics"},
{breadth_name: "Wakanda: African Futures in Education"},
{breadth_name: "Food for a Healthy Planet"},
{breadth_name: "Sexuality Studies Terms and Debates"},
{breadth_name: "Being Online: Internet Meets Society"},
{breadth_name: "Poetry and Poetics"},
{breadth_name: "Mind, Brain and Behaviour 2"},
{breadth_name: "Environmental Systems Modelling & Design"},
{breadth_name: "Reactivity and Mechanism"},
{breadth_name: "Famine: The Geography of Scarcity"},
{breadth_name: "Race, Ethnicity, and Nationalism"},
{breadth_name: "Techniques in Operations Research"},
{breadth_name: "Survey Design and Analysis"},
{breadth_name: "Linear Algebra"},
{breadth_name: "Construction as Alchemy"},
{breadth_name: "Chinese 2"},
{breadth_name: "Geometry"},
{breadth_name: "Orchestration"},
{breadth_name: "Structural and Metamorphic Geology"},
{breadth_name: "Aboriginal Women and Coloniality"},
{breadth_name: "Popular Music Studies"},
{breadth_name: "Campaigns and Elections"},
{breadth_name: "Romancing the Medieval"},
{breadth_name: "Refugees, Borders, Nationalism"},
{breadth_name: "Auditing and Assurance Services"},
{breadth_name: "Microeconomics"},
{breadth_name: "Brand Management"},
{breadth_name: "Personality and Social Psychology"},
{breadth_name: "Management of Financial Institutions"},
{breadth_name: "Intermediate Macroeconomics"},
{breadth_name: "Offshore Geotechnical Engineering"},
{breadth_name: "Musicals & Society: Oklahoma to Hamilton"},
{breadth_name: "Algorithms and Data Structures"},
{breadth_name: "Problem Solving in Environmental Science"},
{breadth_name: "Music Performance Science"},
{breadth_name: "Vector Calculus"},
{breadth_name: "Chemistry: Reactions and Synthesis"},
{breadth_name: "Advanced Food Analysis"},
{breadth_name: "Monitoring Food and Nutrition Intake"},
{breadth_name: "Probability"},
{breadth_name: "Viscera and Visceral Systems"},
{breadth_name: "Quantum and Thermal Physics"},
{breadth_name: "Nutrition Policy and Public Health"},
{breadth_name: "Companion Animal Biology"},
{breadth_name: "Food Microbiology and Safety"},
{breadth_name: "Calculus 2"},
{breadth_name: "International Finance"},
{breadth_name: "Site Tectonics"},
{breadth_name: "Human Sciences: Human/Nonhuman Encounter"},
{breadth_name: "Animal Systems Analysis"},
{breadth_name: "Business in the Global Economy"},
{breadth_name: "Health & Disease in Wildlife Populations"},
{breadth_name: "Field Botany"},
{breadth_name: "Biology of Australian Flora & Fauna"},
{breadth_name: "The Integrated Brain"},
{breadth_name: "Human Sciences: From Cells to Societies"}

]



